// SPDX-License-Identifier: Apache-2.0

import XCTest
import Foundation
@testable import Compiler
@testable import PatchCLI
import CodeGenerator

/// `patchcli prepare --verify`: diagnostic parsing, error → prepared-view attribution, the
/// demote-and-retry loop (incl. the pre-existing-error re-promotion and the bounded stops), the
/// `native_views:` config round-trip, and the prepare/fingerprint consistency of a kept-native view.
final class PrepareVerifierTests: XCTestCase {

    typealias D = PrepareVerifier.Diagnostic

    // MARK: - Diagnostics

    func testParseDiagnosticsExtractsErrorsOnlyAndDedupes() {
        let log = """
        Compiling VerifyApp ProfileCard.swift
        /tmp/p/App/Patch/Generated/PatchThunks.generated.swift:79:86: error: cannot find 'AvatarBadge' in scope
        /tmp/p/App/Patch/Generated/PatchThunks.generated.swift:79:86: error: cannot find 'AvatarBadge' in scope
        /tmp/p/App/Speed.swift:318:33: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
        /tmp/p/App/Speed.swift:12:5: warning: variable 'x' was never used
        ld: error: something not swift
        """
        let ds = PrepareVerifier.parseDiagnostics(log)
        XCTAssertEqual(ds.count, 2)
        XCTAssertEqual(ds[0], D(file: "/tmp/p/App/Patch/Generated/PatchThunks.generated.swift", line: 79, column: 86,
                                message: "cannot find 'AvatarBadge' in scope"))
        XCTAssertEqual(ds[1].line, 318)
        XCTAssertEqual(ds[1].column, 33)
        XCTAssertTrue(ds[1].message.hasPrefix("the compiler is unable to type-check"))
    }

    // MARK: - Attribution

    static let appFile = """
    import SwiftUI

    struct Helper { let x = 1 }

    struct SpeedToolPanel: View {
        let speed: Double
        dynamic var body: some View {
            VStack {
                Text("\\(speed)")
            }
        }
    }

    struct Other: View {
        dynamic var body: some View { Text("o") }
    }

    // PATCH-THUNKS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)
    #if canImport(SwiftUI)
    extension SpeedToolPanel {
        @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
            var __s: [String: ([String]) -> AnyView] = [:]
            __s["op_1"] = { (_: [String]) -> AnyView in AnyView(Text("x")) }
            return __s
        }
    }
    #endif
    // PATCH-THUNKS-END
    """

    static let generatedFile = """
    // PatchThunks.generated.swift — GENERATED BY `patchcli prepare`. DO NOT EDIT.
    #if canImport(SwiftUI)
    import SwiftUI
    extension ProfileCard {
        @_dynamicReplacement(for: body)
        var __patchedBody: some View { body }
    }

    extension ProfileCard {
        @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
            var __s: [String: ([String]) -> AnyView] = [:]
            __s["op_2"] = { (_: [String]) -> AnyView in AnyView(AvatarBadge(initials: initials)) }
            return __s
        }
    }
    #endif
    """

    func testAttributionMapsGeneratedFileInFileBlockAndViewBody() {
        let files = ["/p/App/Speed.swift": Self.appFile,
                     "/p/App/Patch/Generated/PatchThunks.generated.swift": Self.generatedFile]
        let diags = [
            D(file: "/p/App/Patch/Generated/PatchThunks.generated.swift", line: 12, column: 70, message: "cannot find 'AvatarBadge' in scope"),
            D(file: "/p/App/Speed.swift", line: 7, column: 33, message: "the compiler is unable to type-check this expression in reasonable time"),
            D(file: "/p/App/Speed.swift", line: 23, column: 9, message: "cannot convert value"),
            D(file: "/p/App/Speed.swift", line: 3, column: 16, message: "pre-existing error outside any view"),
            D(file: "/p/App/Missing.swift", line: 1, column: 1, message: "unreadable file"),
        ]
        let a = PrepareVerifier.attribute(diags, preparedViews: ["SpeedToolPanel", "ProfileCard", "Other"],
                                          readFile: { files[$0] })
        XCTAssertEqual(a.byView["ProfileCard"]?.count, 1, "generated-file error → the enclosing extension's view")
        XCTAssertEqual(a.byView["SpeedToolPanel"]?.map(\.line), [7, 23],
                       "body-getter timeout + in-file block error → the view")
        XCTAssertNil(a.byView["Other"])
        XCTAssertEqual(a.unattributed.map(\.line), [3, 1], "non-view lines and unreadable files stay unattributed")

        // A view that is NOT currently prepared is never a candidate.
        let b = PrepareVerifier.attribute([diags[1]], preparedViews: ["ProfileCard"], readFile: { files[$0] })
        XCTAssertTrue(b.byView.isEmpty)
        XCTAssertEqual(b.unattributed.count, 1)
    }

    // MARK: - The loop

    private func outcome(_ lines: [String], exit: Int32 = 1, timedOut: Bool = false) -> PrepareVerifier.BuildOutcome {
        PrepareVerifier.BuildOutcome(log: lines.joined(separator: "\n"), exitCode: lines.isEmpty && !timedOut ? exit : 1,
                                     timedOut: timedOut, seconds: 1)
    }

    func testLoopDemotesTheBreakingViewAndEndsClean() throws {
        let files = ["/p/G/PatchThunks.generated.swift": Self.generatedFile, "/p/App/Speed.swift": Self.appFile]
        var native: Set<String> = []
        var applied: [Set<String>] = []
        let report = try PrepareVerifier.run(
            preparedViews: ["ProfileCard", "SpeedToolPanel", "Other"], keptNative: [],
            apply: { n in applied.append(n); native = n
                     return Set(["ProfileCard", "SpeedToolPanel", "Other"]).subtracting(n) },
            build: {
                native.contains("ProfileCard")
                    ? self.outcome([], exit: 0)
                    : self.outcome(["/p/G/PatchThunks.generated.swift:12:70: error: cannot find 'AvatarBadge' in scope"])
            },
            readFile: { files[$0] })
        XCTAssertTrue(report.clean)
        XCTAssertEqual(report.builds, 2)
        XCTAssertEqual(report.demoted.map(\.view), ["ProfileCard"])
        XCTAssertEqual(applied, [["ProfileCard"]], "only the breaking view is kept native")
        XCTAssertTrue(report.preExisting.isEmpty)
    }

    func testLoopRepromotesAViewWhoseErrorIsPreExisting() throws {
        let files = ["/p/App/Speed.swift": Self.appFile]
        var applied: [Set<String>] = []
        // The error is in the ORIGINAL body and persists no matter what prepare does.
        let err = "/p/App/Speed.swift:9:17: error: cannot find 'speedz' in scope"
        let report = try PrepareVerifier.run(
            preparedViews: ["SpeedToolPanel", "Other"], keptNative: ["Legacy"],
            apply: { n in applied.append(n); return Set(["SpeedToolPanel", "Other"]).subtracting(n) },
            build: { self.outcome([err]) },
            readFile: { files[$0] })
        XCTAssertFalse(report.clean)
        XCTAssertTrue(report.demoted.isEmpty, "a pre-existing error must not leave the view native")
        XCTAssertEqual(report.preExisting.map(\.line), [9])
        XCTAssertEqual(applied, [["Legacy", "SpeedToolPanel"], ["Legacy"]],
                       "demote, then re-promote; config-kept views are never touched")
        XCTAssertEqual(report.builds, 3)
    }

    /// The E2E-found case: a body-getter type-check timeout that is the developer's own is
    /// reported at the body's `{` — whose COLUMN moves by 8 when the `dynamic ` prepare inserted
    /// is removed. It must still be recognized as the same (pre-existing) error.
    func testLoopRepromotesWhenOnlyTheColumnShiftsAfterDynamicIsRemoved() throws {
        let files = ["/p/App/Speed.swift": Self.appFile]
        var native: Set<String> = []
        var applied: [Set<String>] = []
        let msg = "the compiler is unable to type-check this expression in reasonable time"
        let report = try PrepareVerifier.run(
            preparedViews: ["SpeedToolPanel"], keptNative: [],
            apply: { n in applied.append(n); native = n; return Set(["SpeedToolPanel"]).subtracting(n) },
            build: {
                // `dynamic var body: some View {` → col 33; `var body: some View {` → col 25.
                self.outcome(["/p/App/Speed.swift:7:\(native.contains("SpeedToolPanel") ? 25 : 33): error: \(msg)"])
            },
            readFile: { files[$0] })
        XCTAssertTrue(report.demoted.isEmpty, "the timeout is pre-existing — the view must be re-promoted")
        XCTAssertEqual(report.preExisting.count, 1)
        XCTAssertEqual(applied, [["SpeedToolPanel"], []])
    }

    func testLoopStopsOnTimeoutAndOnFailureWithoutDiagnostics() throws {
        var applyCalls = 0
        let timedOut = try PrepareVerifier.run(
            preparedViews: ["A"], keptNative: [], apply: { _ in applyCalls += 1; return [] },
            build: { self.outcome([], timedOut: true) }, readFile: { _ in nil })
        XCTAssertTrue(timedOut.timedOut)
        XCTAssertTrue(timedOut.demoted.isEmpty)

        let noDiags = try PrepareVerifier.run(
            preparedViews: ["A"], keptNative: [], apply: { _ in applyCalls += 1; return [] },
            build: { PrepareVerifier.BuildOutcome(log: "error: Dependencies could not be resolved", exitCode: 1,
                                                  timedOut: false, seconds: 1) },
            readFile: { _ in nil })
        XCTAssertNotNil(noDiags.inconclusive)
        XCTAssertEqual(applyCalls, 0, "nothing attributable → nothing is ever demoted")
    }

    func testDetectBuildPrefersXcodeContainerThenPackage() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("verify-detect-\(UUID().uuidString)")
        try fm.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        XCTAssertNil(PrepareVerifier.detectBuild(root: root, scheme: nil))
        try "// swift-tools-version:5.9".write(to: root.appendingPathComponent("Package.swift"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PrepareVerifier.detectBuild(root: root, scheme: nil)?.executable, "/usr/bin/swift")
        try fm.createDirectory(at: root.appendingPathComponent("Shop.xcodeproj"), withIntermediateDirectories: true)
        let x = try XCTUnwrap(PrepareVerifier.detectBuild(root: root, scheme: nil))
        XCTAssertEqual(x.executable, "/usr/bin/xcodebuild")
        XCTAssertTrue(x.arguments.contains("Shop"), "scheme defaults to the project name: \(x.arguments)")
        XCTAssertTrue(x.arguments.contains("generic/platform=iOS Simulator"))
        XCTAssertEqual(PrepareVerifier.detectBuild(root: root, scheme: "ShopApp")?.label, "xcodebuild -scheme ShopApp")
    }

    // MARK: - Configurations (Debug + the archive configuration)

    func testArchiveConfigurationComesFromTheSchemeArchiveAction() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("verify-archive-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: root) }
        let shared = root.appendingPathComponent("Shop.xcodeproj/xcshareddata/xcschemes")
        try fm.createDirectory(at: shared, withIntermediateDirectories: true)
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: "Shop"), "Release",
                       "no scheme file → Xcode's default archive configuration")

        func scheme(_ archive: String) -> String {
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <Scheme LastUpgradeVersion = "2600" version = "1.7">
               <LaunchAction buildConfiguration = "Debug"></LaunchAction>
               <ArchiveAction
                  buildConfiguration = "\(archive)"
                  revealArchiveInOrganizer = "YES">
               </ArchiveAction>
            </Scheme>
            """
        }
        try scheme("AppStore").write(to: shared.appendingPathComponent("Shop.xcscheme"), atomically: true, encoding: .utf8)
        try scheme("Beta").write(to: shared.appendingPathComponent("ShopBeta.xcscheme"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: "Shop"), "AppStore")
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: "ShopBeta"), "Beta")
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: nil), "AppStore",
                       "no scheme named → the scheme named like the project")
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: "Missing"), "AppStore")

        // A per-user scheme counts too.
        let user = root.appendingPathComponent("Shop.xcodeproj/xcuserdata/dev.xcuserdatad/xcschemes")
        try fm.createDirectory(at: user, withIntermediateDirectories: true)
        try scheme("Staging").write(to: user.appendingPathComponent("Internal.xcscheme"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(root: root, scheme: "Internal"), "Staging")

        XCTAssertNil(PrepareVerifier.archiveConfiguration(schemeXML: "<Scheme><LaunchAction buildConfiguration = \"Debug\"/></Scheme>"))
        XCTAssertEqual(PrepareVerifier.archiveConfiguration(schemeXML: "<ArchiveAction buildConfiguration=\"Release\">"), "Release")
    }

    func testVerificationBuildsFollowThePlan() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("verify-plan-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: root) }
        try fm.createDirectory(at: root.appendingPathComponent("Shop.xcodeproj"), withIntermediateDirectories: true)

        let all = PrepareVerifier.verificationBuilds(root: root, scheme: "Shop", plan: .all)
        XCTAssertEqual(all.count, 2)
        XCTAssertFalse(all[0].arguments.contains("-configuration"), "Debug first: the scheme's default build")
        XCTAssertEqual(Array(all[1].arguments.drop { $0 != "-configuration" }.prefix(2)), ["-configuration", "Release"])
        XCTAssertEqual(all[1].label, "xcodebuild -scheme Shop -configuration Release")
        XCTAssertEqual(PrepareVerifier.verificationBuilds(root: root, scheme: "Shop", plan: .debug).count, 1)
        let release = PrepareVerifier.verificationBuilds(root: root, scheme: "Shop", plan: .release)
        XCTAssertEqual(release.map(\.label), ["xcodebuild -scheme Shop -configuration Release"])

        // A scheme that archives with Debug is built once.
        let shared = root.appendingPathComponent("Shop.xcodeproj/xcshareddata/xcschemes")
        try fm.createDirectory(at: shared, withIntermediateDirectories: true)
        try "<Scheme><ArchiveAction buildConfiguration = \"Debug\"></ArchiveAction></Scheme>"
            .write(to: shared.appendingPathComponent("Shop.xcscheme"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PrepareVerifier.verificationBuilds(root: root, scheme: "Shop", plan: .all).count, 1)

        // SwiftPM: `swift build`, then `swift build -c release`.
        let pkg = fm.temporaryDirectory.appendingPathComponent("verify-plan-pkg-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: pkg) }
        try fm.createDirectory(at: pkg, withIntermediateDirectories: true)
        try "// swift-tools-version:5.9".write(to: pkg.appendingPathComponent("Package.swift"), atomically: true, encoding: .utf8)
        let spm = PrepareVerifier.verificationBuilds(root: pkg, scheme: nil, plan: .all)
        XCTAssertEqual(spm.map(\.label), ["swift build", "swift build -c release"])
        XCTAssertEqual(Array(spm[1].arguments.suffix(2)), ["-c", "release"])

        XCTAssertEqual(PrepareVerifier.ConfigurationPlan(argument: "Release"), .release)
        XCTAssertEqual(PrepareVerifier.ConfigurationPlan(argument: "archive"), .release)
        XCTAssertEqual(PrepareVerifier.ConfigurationPlan(argument: "both"), .all)
        XCTAssertNil(PrepareVerifier.ConfigurationPlan(argument: "profile"))
    }

    // MARK: - Compiler crashes + systemic failures

    static let crashLog = """
    SwiftCompile normal arm64 Compiling\\ PatchThunks.generated.swift (in target 'Shop' from project 'Shop')
    Stack dump:
    0.\tProgram arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -O -whole-module-optimization
    1.\tApple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
    2.\tCompiling with effective version 5.10
    3.\tWhile evaluating request IRGenRequest(IR Generation for module 'Shop')
    4.\tWhile emitting IR SIL function "@$s4Shop11ProfileCardV13__patchedBodyQrvg".
     for getter for __patchedBody (at /p/App/Patch/Generated/PatchThunks.generated.swift:12:9)
    Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
    0  swift-frontend           0x0000000108d1c2b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
    1  swift-frontend           0x0000000108d1a3d8 llvm::sys::RunSignalHandlers() + 112
    error: compile command failed due to signal 6 (use -v to see invocation)
    ** BUILD FAILED **
    """

    func testParseCompilerCrashesAttributesTheInnermostFrame() {
        let crashes = PrepareVerifier.parseCompilerCrashes(Self.crashLog)
        XCTAssertEqual(crashes, [D(file: "/p/App/Patch/Generated/PatchThunks.generated.swift", line: 12, column: 9,
                                   message: PrepareVerifier.compilerCrashMessage)])
        XCTAssertTrue(PrepareVerifier.parseDiagnostics(Self.crashLog).isEmpty, "a crash has no file:line error")
        XCTAssertTrue(PrepareVerifier.parseCompilerCrashes("error: compile command failed due to signal 6").isEmpty,
                      "no stack dump → nothing to attribute")
        let files = ["/p/App/Patch/Generated/PatchThunks.generated.swift": Self.generatedFile]
        let a = PrepareVerifier.attribute(crashes, preparedViews: ["ProfileCard"], readFile: { files[$0] })
        XCTAssertEqual(a.byView["ProfileCard"]?.count, 1, "the crash is attributed to the view whose thunk it is in")
    }

    /// A generated file with one replacement per view (every view shares the thunk shape).
    static func generated(_ views: [String]) -> String {
        "// PatchThunks.generated.swift — GENERATED BY `patchcli prepare`. DO NOT EDIT.\nimport SwiftUI\n"
            + views.map { "extension \($0) {\n    @_dynamicReplacement(for: body)\n    var __patchedBody: some View { body }\n}\n" }
                .joined()
    }

    func testLoopStopsWithoutDemotingWhenMostViewsFailInGeneratedCode() throws {
        let views = ["A", "B", "C", "D"]
        let gen = "/p/G/PatchThunks.generated.swift"
        let files = [gen: Self.generated(views)]
        var applyCalls = 0
        // Line 4 / 8 / 12 / 16 are the four `@_dynamicReplacement` getters.
        let log = views.indices.map { "\(gen):\(4 * $0 + 5):5: error: cannot find 'ThemeColor' in scope" }
        let report = try PrepareVerifier.run(
            preparedViews: Set(views), keptNative: [],
            apply: { _ in applyCalls += 1; return Set(views) },
            build: { self.outcome(Array(log.prefix(3))) },
            readFile: { files[$0] })
        let systemic = try XCTUnwrap(report.systemic, "3 of 4 views failing in generated code is a Patch bug")
        XCTAssertEqual(systemic.failingViews, ["A", "B", "C"])
        XCTAssertEqual(systemic.preparedCount, 4)
        XCTAssertFalse(systemic.compilerCrash)
        XCTAssertTrue(report.demoted.isEmpty, "nothing is kept native for a systemic failure")
        XCTAssertEqual(applyCalls, 0)
        XCTAssertEqual(report.builds, 1)
        XCTAssertNil(report.inconclusive)
    }

    func testAMinorityOfGeneratedFailuresIsStillDemotedPerView() throws {
        let views = ["A", "B", "C", "D"]
        let gen = "/p/G/PatchThunks.generated.swift"
        let files = [gen: Self.generated(views)]
        var native: Set<String> = []
        let report = try PrepareVerifier.run(
            preparedViews: Set(views), keptNative: [],
            apply: { n in native = n; return Set(views).subtracting(n) },
            build: {
                // Two of four (not MORE than half) → per-view demotion, as before.
                let errs = ["A", "B"].filter { !native.contains($0) }
                    .map { v in "\(gen):\(4 * views.firstIndex(of: v)! + 5):5: error: ambiguous use of 'init'" }
                return errs.isEmpty ? self.outcome([], exit: 0) : self.outcome(errs)
            },
            readFile: { files[$0] })
        XCTAssertNil(report.systemic)
        XCTAssertTrue(report.clean)
        XCTAssertEqual(Set(report.demoted.map(\.view)), ["A", "B"])
    }

    /// A whole-module (Release) build stops at its FIRST crash, so a compiler crash on the thunk
    /// pattern itself surfaces one view per build. The second crashing view proves it is systemic:
    /// stop, and give the first view its thunk back.
    func testRepeatedCompilerCrashAcrossRoundsIsSystemicAndUndoesTheCrashDemotion() throws {
        let views = ["A", "B", "C", "D", "E", "F"]
        let gen = "/p/G/PatchThunks.generated.swift"
        let files = [gen: Self.generated(views)]
        var native: Set<String> = []
        var applied: [Set<String>] = []
        func crash(at view: String) -> String {
            Self.crashLog.replacingOccurrences(of: "/p/App/Patch/Generated/PatchThunks.generated.swift:12:9",
                                               with: "\(gen):\(4 * views.firstIndex(of: view)! + 5):9")
        }
        let report = try PrepareVerifier.run(
            preparedViews: Set(views), keptNative: ["Legacy"],
            apply: { n in applied.append(n); native = n; return Set(views).subtracting(n) },
            build: {
                let next = views.first { !native.contains($0) }!
                return PrepareVerifier.BuildOutcome(log: crash(at: next), exitCode: 65, timedOut: false, seconds: 1)
            },
            readFile: { files[$0] })
        let systemic = try XCTUnwrap(report.systemic)
        XCTAssertTrue(systemic.compilerCrash)
        XCTAssertEqual(systemic.failingViews, ["A", "B"])
        XCTAssertEqual(report.builds, 2)
        XCTAssertTrue(report.demoted.isEmpty, "the crash demotion from round 1 is undone")
        XCTAssertEqual(applied, [["Legacy", "A"], ["Legacy"]], "config-kept views stay native throughout")
    }

    /// The real-app sequence (Xcode 16.1, `-configuration Release`, the prepared HelloXcode26 fixture):
    /// the whole-module compile crashed at `PatchThunks.generated.swift:56:9` (ContentView's getter);
    /// ContentView was demoted, the generated file regenerated, and the NEXT view's getter now sat at
    /// 56:9 and crashed identically. The old loop took the identical file:line:message as proof the
    /// error was the project's own and re-promoted ContentView, ending "inconclusive". A diagnostic in
    /// regenerated code is never evidence of a pre-existing error — this is a systemic Patch bug.
    func testSameLocationCrashAfterRegenerationIsSystemicNotPreExisting() throws {
        let views = ["ContentView", "SettingsPanel", "TaskRow"]
        let gen = "/p/G/PatchThunks.generated.swift"
        var files = [gen: Self.generated(views)]
        var native: Set<String> = []
        let log = Self.crashLog.replacingOccurrences(of: "/p/App/Patch/Generated/PatchThunks.generated.swift:12:9",
                                                     with: "\(gen):5:9")
        let report = try PrepareVerifier.run(
            preparedViews: Set(views), keptNative: [],
            apply: { n in
                native = n
                let left = views.filter { !n.contains($0) }
                files[gen] = Self.generated(left)
                return Set(left)
            },
            build: { PrepareVerifier.BuildOutcome(log: log, exitCode: 65, timedOut: false, seconds: 1) },
            readFile: { files[$0] })
        let systemic = try XCTUnwrap(report.systemic, "inconclusive: \(report.inconclusive ?? "-"), pre-existing: \(report.preExisting)")
        XCTAssertTrue(systemic.compilerCrash)
        XCTAssertEqual(systemic.failingViews, ["ContentView", "SettingsPanel"])
        XCTAssertTrue(report.demoted.isEmpty)
        XCTAssertTrue(report.preExisting.isEmpty, "a generated-code crash is never the project's own error")
        XCTAssertTrue(native.isEmpty, "the crash demotion is undone")
        XCTAssertEqual(files[gen], Self.generated(views))
    }

    func testASingleCompilerCrashInOneViewIsDemotedLikeAnError() throws {
        let views = ["A", "B", "C", "D"]
        let gen = "/p/G/PatchThunks.generated.swift"
        let files = [gen: Self.generated(views)]
        var native: Set<String> = []
        let log = Self.crashLog.replacingOccurrences(of: "/p/App/Patch/Generated/PatchThunks.generated.swift:12:9",
                                                     with: "\(gen):9:9")
        let report = try PrepareVerifier.run(
            preparedViews: Set(views), keptNative: [],
            apply: { n in native = n; return Set(views).subtracting(n) },
            build: {
                native.contains("B")
                    ? self.outcome([], exit: 0)
                    : PrepareVerifier.BuildOutcome(log: log, exitCode: 65, timedOut: false, seconds: 1)
            },
            readFile: { files[$0] })
        XCTAssertNil(report.systemic)
        XCTAssertTrue(report.clean)
        XCTAssertEqual(report.demoted.map(\.view), ["B"])
    }

    func testSystemicFailureMessageNamesPatchAndIsActionable() {
        let s = PrepareVerifier.SystemicFailure(
            failingViews: ["A", "B", "C"], preparedCount: 4, compilerCrash: true,
            example: D(file: "/p/PatchThunks.generated.swift", line: 9, column: 9, message: PrepareVerifier.compilerCrashMessage))
        let m = Prepare.systemicFailureMessage(s, buildLabel: "xcodebuild -scheme Shop -configuration Release")
        XCTAssertTrue(m.contains("PATCH BUG"))
        XCTAssertTrue(m.contains("patchcli \(Patch.configuration.version)"))
        XCTAssertTrue(m.contains("crashes the Swift compiler in 3 of 4"))
        XCTAssertTrue(m.contains("-configuration Release"))
        XCTAssertTrue(m.contains("patchcli unprepare"))
    }

    // MARK: - native_views config

    func testNativeViewsConfigRoundTripsAndIsAbsentWhenEmpty() throws {
        var cfg = PatchConfig(appKey: "pak_x", project: "P", target: "T")
        XCTAssertFalse(cfg.yamlString().contains("native_views"), "existing configs serialize byte-identically")
        cfg.nativeViews = ["SpeedToolPanel", "OnboardingScreen"]
        let parsed = try PatchConfig.parse(cfg.yamlString())
        XCTAssertEqual(parsed.nativeViews, ["SpeedToolPanel", "OnboardingScreen"])
        XCTAssertEqual(parsed, cfg)

        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("native-views-\(UUID().uuidString)")
        try fm.createDirectory(at: root.appendingPathComponent("App/Views"), withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        try cfg.yamlString().write(to: root.appendingPathComponent(".Patch.yml"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PatchConfig.nativeViewNames(near: root.appendingPathComponent("App/Views")),
                       ["SpeedToolPanel", "OnboardingScreen"])
    }

    // MARK: - Kept-native views: prepare restores the source, fingerprint keeps the body hashed

    static let twoViews = """
    import SwiftUI
    struct Keep: View {
        var body: some View { Text("keep") }
    }
    struct Drop: View {
        var body: some View { Text("drop") }
    }
    """

    func testNativeViewsGetNoThunkAndLosePriorDynamicWhileOthersAreUnchanged() {
        let url = URL(fileURLWithPath: "/tmp/TwoViews.swift")
        let plain = ThunkGenerator().prepare(sources: [.init(url: url, text: Self.twoViews)], hybrid: true)
        XCTAssertEqual(plain.viewNames, ["Drop", "Keep"])
        let prepared = plain.modifiedFiles.first?.text ?? ""
        XCTAssertTrue(prepared.contains("var body: some View { __patchRoute { Text(\"drop\") } }"), prepared)

        // Re-prepare the ALREADY-prepared file keeping `Drop` native.
        let kept = ThunkGenerator().prepare(sources: [.init(url: url, text: prepared)], hybrid: true,
                                            nativeViews: ["Drop"])
        XCTAssertEqual(kept.viewNames, ["Keep"])
        let restored = kept.modifiedFiles.first?.text ?? prepared
        XCTAssertTrue(restored.contains("    var body: some View { Text(\"drop\") }"),
                      "the kept-native view's original source span is restored:\n\(restored)")
        XCTAssertTrue(restored.contains("var body: some View { __patchRoute { Text(\"keep\") } }"), restored)
        XCTAssertFalse(kept.generatedFileContents.contains("extension Drop"))
        // The other view's generated thunk is byte-identical to a run without the list.
        let keepOnlyPlain = plain.generatedFileContents.components(separatedBy: "extension Keep").count
        XCTAssertEqual(kept.generatedFileContents.components(separatedBy: "extension Keep").count, keepOnlyPlain)
        // Round trip: preparing the restored file from scratch with the same list is a no-op.
        let again = ThunkGenerator().prepare(sources: [.init(url: url, text: restored)], hybrid: true,
                                             nativeViews: ["Drop"])
        XCTAssertTrue(again.modifiedFiles.isEmpty)
        XCTAssertEqual(again.generatedFileContents, kept.generatedFileContents)
    }

    func testFingerprintKeepsAKeptNativeViewBodyHashed() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("native-fp-\(UUID().uuidString)")
        try fm.createDirectory(at: root.appendingPathComponent("App"), withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        try """
        import SwiftUI
        struct Card: View {
            var body: some View {
                VStack {
                    Text("Title")
                    Text("Body")
                }
            }
        }
        """.write(to: root.appendingPathComponent("App/Card.swift"), atomically: true, encoding: .utf8)
        let auto = ProjectFingerprinter.loweredAutoRoutedViewData(projectDir: root, registry: .standard)
        try XCTSkipUnless(auto.bodySpansByFile.values.contains(where: { !$0.isEmpty }),
                          "Card did not auto-route in this engine build — skip")
        var cfg = PatchConfig(appKey: "pak_x", project: "P", target: "T")
        cfg.nativeViews = ["Card"]
        try cfg.yamlString().write(to: root.appendingPathComponent(".Patch.yml"), atomically: true, encoding: .utf8)
        let kept = ProjectFingerprinter.loweredAutoRoutedViewData(projectDir: root, registry: .standard)
        XCTAssertTrue(kept.bodySpansByFile.values.allSatisfy { $0.isEmpty },
                      "a kept-native view renders from the binary — its body must stay in the fingerprint")
    }
}
