// SPDX-License-Identifier: Apache-2.0

import XCTest
import Foundation
@testable import Compiler
import CodeGenerator

/// `patchcli prepare --verify`: diagnostic parsing, error → prepared-view attribution, the
/// demote-and-retry loop (incl. the pre-existing-error re-promotion and the bounded stops), the
/// `native_views:` config round-trip, and the prepare/fingerprint consistency of a kept-native view.
final class PrepareVerifierTests: XCTestCase {

    typealias D = PrepareVerifier.Diagnostic

    // MARK: - Diagnostics

    func testParseDiagnosticsExtractsErrorsOnlyAndDedupes() {
        let log = """
        Compiling VerifyApp ProfileCard.swift
        /tmp/p/App/Patch/Generated/PatchThunks.generated.swift:79:86: error: cannot find 'AvatarBadge' in scope
        /tmp/p/App/Patch/Generated/PatchThunks.generated.swift:79:86: error: cannot find 'AvatarBadge' in scope
        /tmp/p/App/Speed.swift:318:33: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
        /tmp/p/App/Speed.swift:12:5: warning: variable 'x' was never used
        ld: error: something not swift
        """
        let ds = PrepareVerifier.parseDiagnostics(log)
        XCTAssertEqual(ds.count, 2)
        XCTAssertEqual(ds[0], D(file: "/tmp/p/App/Patch/Generated/PatchThunks.generated.swift", line: 79, column: 86,
                                message: "cannot find 'AvatarBadge' in scope"))
        XCTAssertEqual(ds[1].line, 318)
        XCTAssertEqual(ds[1].column, 33)
        XCTAssertTrue(ds[1].message.hasPrefix("the compiler is unable to type-check"))
    }

    // MARK: - Attribution

    static let appFile = """
    import SwiftUI

    struct Helper { let x = 1 }

    struct SpeedToolPanel: View {
        let speed: Double
        dynamic var body: some View {
            VStack {
                Text("\\(speed)")
            }
        }
    }

    struct Other: View {
        dynamic var body: some View { Text("o") }
    }

    // PATCH-THUNKS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)
    #if canImport(SwiftUI)
    extension SpeedToolPanel {
        @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
            var __s: [String: ([String]) -> AnyView] = [:]
            __s["op_1"] = { (_: [String]) -> AnyView in AnyView(Text("x")) }
            return __s
        }
    }
    #endif
    // PATCH-THUNKS-END
    """

    static let generatedFile = """
    // PatchThunks.generated.swift — GENERATED BY `patchcli prepare`. DO NOT EDIT.
    #if canImport(SwiftUI)
    import SwiftUI
    extension ProfileCard {
        @_dynamicReplacement(for: body)
        var __patchedBody: some View { body }
    }

    extension ProfileCard {
        @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
            var __s: [String: ([String]) -> AnyView] = [:]
            __s["op_2"] = { (_: [String]) -> AnyView in AnyView(AvatarBadge(initials: initials)) }
            return __s
        }
    }
    #endif
    """

    func testAttributionMapsGeneratedFileInFileBlockAndViewBody() {
        let files = ["/p/App/Speed.swift": Self.appFile,
                     "/p/App/Patch/Generated/PatchThunks.generated.swift": Self.generatedFile]
        let diags = [
            D(file: "/p/App/Patch/Generated/PatchThunks.generated.swift", line: 12, column: 70, message: "cannot find 'AvatarBadge' in scope"),
            D(file: "/p/App/Speed.swift", line: 7, column: 33, message: "the compiler is unable to type-check this expression in reasonable time"),
            D(file: "/p/App/Speed.swift", line: 23, column: 9, message: "cannot convert value"),
            D(file: "/p/App/Speed.swift", line: 3, column: 16, message: "pre-existing error outside any view"),
            D(file: "/p/App/Missing.swift", line: 1, column: 1, message: "unreadable file"),
        ]
        let a = PrepareVerifier.attribute(diags, preparedViews: ["SpeedToolPanel", "ProfileCard", "Other"],
                                          readFile: { files[$0] })
        XCTAssertEqual(a.byView["ProfileCard"]?.count, 1, "generated-file error → the enclosing extension's view")
        XCTAssertEqual(a.byView["SpeedToolPanel"]?.map(\.line), [7, 23],
                       "body-getter timeout + in-file block error → the view")
        XCTAssertNil(a.byView["Other"])
        XCTAssertEqual(a.unattributed.map(\.line), [3, 1], "non-view lines and unreadable files stay unattributed")

        // A view that is NOT currently prepared is never a candidate.
        let b = PrepareVerifier.attribute([diags[1]], preparedViews: ["ProfileCard"], readFile: { files[$0] })
        XCTAssertTrue(b.byView.isEmpty)
        XCTAssertEqual(b.unattributed.count, 1)
    }

    // MARK: - The loop

    private func outcome(_ lines: [String], exit: Int32 = 1, timedOut: Bool = false) -> PrepareVerifier.BuildOutcome {
        PrepareVerifier.BuildOutcome(log: lines.joined(separator: "\n"), exitCode: lines.isEmpty && !timedOut ? exit : 1,
                                     timedOut: timedOut, seconds: 1)
    }

    func testLoopDemotesTheBreakingViewAndEndsClean() throws {
        let files = ["/p/G/PatchThunks.generated.swift": Self.generatedFile, "/p/App/Speed.swift": Self.appFile]
        var native: Set<String> = []
        var applied: [Set<String>] = []
        let report = try PrepareVerifier.run(
            preparedViews: ["ProfileCard", "SpeedToolPanel", "Other"], keptNative: [],
            apply: { n in applied.append(n); native = n
                     return Set(["ProfileCard", "SpeedToolPanel", "Other"]).subtracting(n) },
            build: {
                native.contains("ProfileCard")
                    ? self.outcome([], exit: 0)
                    : self.outcome(["/p/G/PatchThunks.generated.swift:12:70: error: cannot find 'AvatarBadge' in scope"])
            },
            readFile: { files[$0] })
        XCTAssertTrue(report.clean)
        XCTAssertEqual(report.builds, 2)
        XCTAssertEqual(report.demoted.map(\.view), ["ProfileCard"])
        XCTAssertEqual(applied, [["ProfileCard"]], "only the breaking view is kept native")
        XCTAssertTrue(report.preExisting.isEmpty)
    }

    func testLoopRepromotesAViewWhoseErrorIsPreExisting() throws {
        let files = ["/p/App/Speed.swift": Self.appFile]
        var applied: [Set<String>] = []
        // The error is in the ORIGINAL body and persists no matter what prepare does.
        let err = "/p/App/Speed.swift:9:17: error: cannot find 'speedz' in scope"
        let report = try PrepareVerifier.run(
            preparedViews: ["SpeedToolPanel", "Other"], keptNative: ["Legacy"],
            apply: { n in applied.append(n); return Set(["SpeedToolPanel", "Other"]).subtracting(n) },
            build: { self.outcome([err]) },
            readFile: { files[$0] })
        XCTAssertFalse(report.clean)
        XCTAssertTrue(report.demoted.isEmpty, "a pre-existing error must not leave the view native")
        XCTAssertEqual(report.preExisting.map(\.line), [9])
        XCTAssertEqual(applied, [["Legacy", "SpeedToolPanel"], ["Legacy"]],
                       "demote, then re-promote; config-kept views are never touched")
        XCTAssertEqual(report.builds, 3)
    }

    /// The E2E-found case: a body-getter type-check timeout that is the developer's own is
    /// reported at the body's `{` — whose COLUMN moves by 8 when the `dynamic ` prepare inserted
    /// is removed. It must still be recognized as the same (pre-existing) error.
    func testLoopRepromotesWhenOnlyTheColumnShiftsAfterDynamicIsRemoved() throws {
        let files = ["/p/App/Speed.swift": Self.appFile]
        var native: Set<String> = []
        var applied: [Set<String>] = []
        let msg = "the compiler is unable to type-check this expression in reasonable time"
        let report = try PrepareVerifier.run(
            preparedViews: ["SpeedToolPanel"], keptNative: [],
            apply: { n in applied.append(n); native = n; return Set(["SpeedToolPanel"]).subtracting(n) },
            build: {
                // `dynamic var body: some View {` → col 33; `var body: some View {` → col 25.
                self.outcome(["/p/App/Speed.swift:7:\(native.contains("SpeedToolPanel") ? 25 : 33): error: \(msg)"])
            },
            readFile: { files[$0] })
        XCTAssertTrue(report.demoted.isEmpty, "the timeout is pre-existing — the view must be re-promoted")
        XCTAssertEqual(report.preExisting.count, 1)
        XCTAssertEqual(applied, [["SpeedToolPanel"], []])
    }

    func testLoopStopsOnTimeoutAndOnFailureWithoutDiagnostics() throws {
        var applyCalls = 0
        let timedOut = try PrepareVerifier.run(
            preparedViews: ["A"], keptNative: [], apply: { _ in applyCalls += 1; return [] },
            build: { self.outcome([], timedOut: true) }, readFile: { _ in nil })
        XCTAssertTrue(timedOut.timedOut)
        XCTAssertTrue(timedOut.demoted.isEmpty)

        let noDiags = try PrepareVerifier.run(
            preparedViews: ["A"], keptNative: [], apply: { _ in applyCalls += 1; return [] },
            build: { PrepareVerifier.BuildOutcome(log: "error: Dependencies could not be resolved", exitCode: 1,
                                                  timedOut: false, seconds: 1) },
            readFile: { _ in nil })
        XCTAssertNotNil(noDiags.inconclusive)
        XCTAssertEqual(applyCalls, 0, "nothing attributable → nothing is ever demoted")
    }

    func testDetectBuildPrefersXcodeContainerThenPackage() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("verify-detect-\(UUID().uuidString)")
        try fm.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        XCTAssertNil(PrepareVerifier.detectBuild(root: root, scheme: nil))
        try "// swift-tools-version:5.9".write(to: root.appendingPathComponent("Package.swift"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PrepareVerifier.detectBuild(root: root, scheme: nil)?.executable, "/usr/bin/swift")
        try fm.createDirectory(at: root.appendingPathComponent("Shop.xcodeproj"), withIntermediateDirectories: true)
        let x = try XCTUnwrap(PrepareVerifier.detectBuild(root: root, scheme: nil))
        XCTAssertEqual(x.executable, "/usr/bin/xcodebuild")
        XCTAssertTrue(x.arguments.contains("Shop"), "scheme defaults to the project name: \(x.arguments)")
        XCTAssertTrue(x.arguments.contains("generic/platform=iOS Simulator"))
        XCTAssertEqual(PrepareVerifier.detectBuild(root: root, scheme: "ShopApp")?.label, "xcodebuild -scheme ShopApp")
    }

    // MARK: - native_views config

    func testNativeViewsConfigRoundTripsAndIsAbsentWhenEmpty() throws {
        var cfg = PatchConfig(appKey: "pak_x", project: "P", target: "T")
        XCTAssertFalse(cfg.yamlString().contains("native_views"), "existing configs serialize byte-identically")
        cfg.nativeViews = ["SpeedToolPanel", "OnboardingScreen"]
        let parsed = try PatchConfig.parse(cfg.yamlString())
        XCTAssertEqual(parsed.nativeViews, ["SpeedToolPanel", "OnboardingScreen"])
        XCTAssertEqual(parsed, cfg)

        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("native-views-\(UUID().uuidString)")
        try fm.createDirectory(at: root.appendingPathComponent("App/Views"), withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        try cfg.yamlString().write(to: root.appendingPathComponent(".Patch.yml"), atomically: true, encoding: .utf8)
        XCTAssertEqual(PatchConfig.nativeViewNames(near: root.appendingPathComponent("App/Views")),
                       ["SpeedToolPanel", "OnboardingScreen"])
    }

    // MARK: - Kept-native views: prepare restores the source, fingerprint keeps the body hashed

    static let twoViews = """
    import SwiftUI
    struct Keep: View {
        var body: some View { Text("keep") }
    }
    struct Drop: View {
        var body: some View { Text("drop") }
    }
    """

    func testNativeViewsGetNoThunkAndLosePriorDynamicWhileOthersAreUnchanged() {
        let url = URL(fileURLWithPath: "/tmp/TwoViews.swift")
        let plain = ThunkGenerator().prepare(sources: [.init(url: url, text: Self.twoViews)], hybrid: true)
        XCTAssertEqual(plain.viewNames, ["Drop", "Keep"])
        let prepared = plain.modifiedFiles.first?.text ?? ""
        XCTAssertTrue(prepared.contains("dynamic var body: some View { Text(\"drop\") }"))

        // Re-prepare the ALREADY-prepared file keeping `Drop` native.
        let kept = ThunkGenerator().prepare(sources: [.init(url: url, text: prepared)], hybrid: true,
                                            nativeViews: ["Drop"])
        XCTAssertEqual(kept.viewNames, ["Keep"])
        let restored = kept.modifiedFiles.first?.text ?? prepared
        XCTAssertTrue(restored.contains("    var body: some View { Text(\"drop\") }"),
                      "the kept-native view's original source span is restored:\n\(restored)")
        XCTAssertTrue(restored.contains("dynamic var body: some View { Text(\"keep\") }"))
        XCTAssertFalse(kept.generatedFileContents.contains("extension Drop"))
        // The other view's generated thunk is byte-identical to a run without the list.
        let keepOnlyPlain = plain.generatedFileContents.components(separatedBy: "extension Keep").count
        XCTAssertEqual(kept.generatedFileContents.components(separatedBy: "extension Keep").count, keepOnlyPlain)
        // Round trip: preparing the restored file from scratch with the same list is a no-op.
        let again = ThunkGenerator().prepare(sources: [.init(url: url, text: restored)], hybrid: true,
                                             nativeViews: ["Drop"])
        XCTAssertTrue(again.modifiedFiles.isEmpty)
        XCTAssertEqual(again.generatedFileContents, kept.generatedFileContents)
    }

    func testFingerprintKeepsAKeptNativeViewBodyHashed() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("native-fp-\(UUID().uuidString)")
        try fm.createDirectory(at: root.appendingPathComponent("App"), withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        try """
        import SwiftUI
        struct Card: View {
            var body: some View {
                VStack {
                    Text("Title")
                    Text("Body")
                }
            }
        }
        """.write(to: root.appendingPathComponent("App/Card.swift"), atomically: true, encoding: .utf8)
        let auto = ProjectFingerprinter.loweredAutoRoutedViewData(projectDir: root, registry: .standard)
        try XCTSkipUnless(auto.bodySpansByFile.values.contains(where: { !$0.isEmpty }),
                          "Card did not auto-route in this engine build — skip")
        var cfg = PatchConfig(appKey: "pak_x", project: "P", target: "T")
        cfg.nativeViews = ["Card"]
        try cfg.yamlString().write(to: root.appendingPathComponent(".Patch.yml"), atomically: true, encoding: .utf8)
        let kept = ProjectFingerprinter.loweredAutoRoutedViewData(projectDir: root, registry: .standard)
        XCTAssertTrue(kept.bodySpansByFile.values.allSatisfy { $0.isEmpty },
                      "a kept-native view renders from the binary — its body must stay in the fingerprint")
    }
}
