// SPDX-License-Identifier: Apache-2.0

// BodyRouting.swift — the source edit `patchcli prepare` makes to a patchable SwiftUI view.
// =============================================================================
// A prepared view's body is WRAPPED in a route call, on the body's own lines:
//
//     var body: some View { __patchRoute {          // was: var body: some View {
//         VStack { … }                               //      VStack { … }
//     } }                                            // was: }
//
// The generated thunk declares, per view, a concrete `func __patchRoute(_:)` on the view type
// that asks the SDK for a patched body and otherwise renders the wrapped native content. A
// `fileprivate extension View { func __patchRoute }` fallback in a small PATCH-ROUTE block at
// the end of the same file renders the content natively whenever no generated route exists
// (a fresh clone without Patch/Generated/, a view kept native) — so the file ALWAYS builds.
// Overload resolution picks the concrete view member over the protocol-extension fallback.
//
// WHY NOT `dynamic` + `@_dynamicReplacement(for: body)` (what prepare used to emit): an
// opaque-result (`some View`) dynamic replacement is broken in optimized builds on every Swift
// toolchain we tested (6.0.2 → 6.3.2, Xcode 16.1 → 26.6):
//   * `-O` IRGen crash (`ElementLayout::project`, Swift ≤ 6.2) when the replacement's result
//     holds the original body's value — the reported Release-archive crash;
//   * `-O -wmo` link failure: the replacement's opaque type descriptor is lazily emitted, but
//     `IRGenerator::emitDynamicReplacements` runs after `emitLazyDefinitions`, so the
//     descriptor it references is never emitted ("undefined opaque type descriptor");
//   * parallel WMO (`-num-threads N`, Xcode's Release default) emits a binary that segfaults
//     at launch whenever the replacement and original land in different object files.
// A plain generic method call has none of these problems, keeps the native body's CONCRETE
// type (`_ConditionalContent<AnyView, NativeBody>` — no `AnyView` erasure of the native path),
// and needs no `dynamic` at all.
//
// Every edit here is byte-exact and same-line (line numbers never move), and has an exact
// inverse (`unrouteBodies`), so unprepare, `native_views:` demotion and the native-shell
// fingerprint (which canonicalizes a routed body back to the legacy `dynamic var body` text,
// keeping existing registered fingerprints valid) are all exact.

import Foundation
import SwiftSyntax
import SwiftParser

extension ThunkGenerator {

    /// The route method every prepared body calls (the generated per-view member and the
    /// in-file native fallback share this name).
    public static let routeMethodName = "__patchRoute"
    /// Inserted right after the body getter's `{`.
    public static let routeOpen = " __patchRoute {"
    /// Inserted right before the body getter's `}`.
    public static let routeClose = "} "
    /// The generic parameter / closure-parameter names of the route method (reserved `__patch`
    /// prefix, so they can't collide with a view's own generic parameters).
    static let routeNativeTypeParam = "__PatchNativeBody"
    static let routeNativeParam = "__nativeBody"

    public static let routeFallbackBeginMarker =
        "// PATCH-ROUTE-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)"
    public static let routeFallbackEndMarker = "// PATCH-ROUTE-END"

    /// The in-file native fallback for `__patchRoute { … }` bodies. File-private, so every
    /// prepared file carries its own copy without redeclaration conflicts; SwiftUI-only (no
    /// PatchSDK import), so the file builds even when the Patch package or the generated folder
    /// is missing. `@inline(__always)` + a concrete generic return: the fallback path costs
    /// nothing over the original body.
    public static let routeFallbackBlock = """
    \(routeFallbackBeginMarker)
    // Renders this file's `__patchRoute { … }` view bodies natively when Patch/Generated/ has no route
    // for the view (e.g. a fresh clone). Regenerated by `patchcli prepare`; removed by `patchcli unprepare`.
    fileprivate extension View {
        @inline(__always) func \(routeMethodName)<\(routeNativeTypeParam): View>(@ViewBuilder _ \(routeNativeParam): () -> \(routeNativeTypeParam)) -> \(routeNativeTypeParam) { \(routeNativeParam)() }
    }
    \(routeFallbackEndMarker)

    """

    // MARK: - Locating bodies

    /// One `var body: some View` getter found in a file.
    public struct BodySite: Equatable {
        /// The innermost enclosing type (struct/extension/enum/class/actor) name.
        public var type: String
        /// UTF-8 offset of the `var` keyword (where legacy prepare inserted `dynamic `).
        public var varOffset: Int
        /// The legacy `dynamic` modifier's byte range incl. the one space after it, if present.
        public var dynamicRange: Range<Int>?
        /// Where `routeOpen` is inserted (right after the getter's `{`) — nil when the getter
        /// has no statements (nothing to route).
        public var openInsertOffset: Int?
        /// Where `routeClose` is inserted (right before the getter's `}`).
        public var closeInsertOffset: Int?
        /// When the body is ALREADY routed: the two byte ranges whose removal restores the
        /// unrouted getter (the `routeOpen` and `routeClose` text).
        public var routeRanges: [Range<Int>]?
        public var isRouted: Bool { routeRanges != nil }
        public var isDynamic: Bool { dynamicRange != nil }
    }

    /// Every `var body: some View` getter outside `#if` in `tree` (any enclosing type).
    public static func bodySites(in tree: SourceFileSyntax) -> [BodySite] {
        let c = BodySiteCollector()
        c.walk(tree)
        return c.sites
    }

    /// The statements a (possibly routed) body getter renders: for a routed getter, the
    /// statements INSIDE the `__patchRoute { … }` closure — so the engine lowers, hashes and
    /// slot-ids a prepared body exactly like the original. Unrouted getters pass through.
    public static func unroutedStatements(_ items: CodeBlockItemListSyntax) -> CodeBlockItemListSyntax {
        routeClosure(of: items)?.statements ?? items
    }

    /// The route call's trailing closure when `items` is exactly `__patchRoute { … }`.
    static func routeClosure(of items: CodeBlockItemListSyntax) -> ClosureExprSyntax? {
        guard items.count == 1, let item = items.first,
              let call = item.item.as(FunctionCallExprSyntax.self)
                ?? item.item.as(ExpressionStmtSyntax.self)?.expression.as(FunctionCallExprSyntax.self),
              let callee = call.calledExpression.as(DeclReferenceExprSyntax.self),
              callee.baseName.text == routeMethodName, callee.argumentNames == nil,
              call.leftParen == nil, call.arguments.isEmpty,
              let closure = call.trailingClosure, call.additionalTrailingClosures.isEmpty,
              closure.signature == nil else { return nil }
        return closure
    }

    // MARK: - Editing

    /// A byte-range replacement (an insertion is an empty range).
    public struct TextEdit: Equatable {
        public var range: Range<Int>
        public var replacement: String
        public init(_ range: Range<Int>, _ replacement: String) { self.range = range; self.replacement = replacement }
    }

    /// Apply non-overlapping `edits` (any order) to `text`, last-first so offsets stay valid.
    public static func apply(_ edits: [TextEdit], to text: String) -> String {
        guard !edits.isEmpty else { return text }
        var bytes = Array(text.utf8)
        for e in edits.sorted(by: { $0.range.lowerBound > $1.range.lowerBound
                                     || ($0.range.lowerBound == $1.range.lowerBound && $0.range.upperBound > $1.range.upperBound) }) {
            guard e.range.lowerBound >= 0, e.range.upperBound <= bytes.count else { continue }
            bytes.replaceSubrange(e.range, with: Array(e.replacement.utf8))
        }
        return String(decoding: bytes, as: UTF8.self)
    }

    /// The edits that route `site` (and, with `removingDynamic`, drop the `dynamic` an older CLI's
    /// prepare inserted). Empty when already routed, or when the getter has nothing to route.
    /// A `dynamic` prepare didn't provably insert stays: `dynamic` alone (with no
    /// `@_dynamicReplacement`) builds and runs correctly in every mode, and it may be the
    /// developer's own (hot-reload tooling).
    static func routeEdits(for site: BodySite, removingDynamic: Bool = false) -> [TextEdit] {
        var edits: [TextEdit] = []
        if removingDynamic, let d = site.dynamicRange { edits.append(TextEdit(d, "")) }
        if !site.isRouted, let open = site.openInsertOffset, let close = site.closeInsertOffset {
            edits.append(TextEdit(open..<open, routeOpen))
            edits.append(TextEdit(close..<close, routeClose))
        }
        return edits
    }

    /// The edits that restore `site`'s original getter (remove the route wrapper and a legacy
    /// `dynamic`).
    static func unrouteEdits(for site: BodySite, removingDynamic: Bool = true) -> [TextEdit] {
        var edits = (site.routeRanges ?? []).map { TextEdit($0, "") }
        if removingDynamic, let d = site.dynamicRange { edits.append(TextEdit(d, "")) }
        return edits
    }

    /// Remove the route wrapper (and, with `removingDynamic`, a legacy `dynamic`) from every
    /// `var body: some View` of `onlyTypes` (all types when nil). Returns the new text and the
    /// type names whose body changed. Exact inverse of prepare's edit.
    public static func unrouteBodies(in source: String, onlyTypes: Set<String>?,
                                     removingDynamic: Bool = true) -> (text: String, types: [String]) {
        guard source.contains(routeMethodName) || (removingDynamic && source.contains("dynamic")) else {
            return (source, [])
        }
        let sites = bodySites(in: Parser.parse(source: source))
            .filter { onlyTypes == nil || onlyTypes!.contains($0.type) }
        var edits: [TextEdit] = []
        var types: [String] = []
        for s in sites {
            let e = unrouteEdits(for: s, removingDynamic: removingDynamic)
            if !e.isEmpty { edits += e; types.append(s.type) }
        }
        return (apply(edits, to: source), types)
    }

    /// True when `source` (ignoring generated blocks) still has a routed body — i.e. needs the
    /// PATCH-ROUTE fallback block to build.
    public static func hasRoutedBody(_ source: String) -> Bool {
        guard source.contains(routeMethodName) else { return false }
        let developer = PatchAccessForwarding.stripAllGeneratedBlocks(from: source)
        guard developer.contains(routeMethodName) else { return false }
        return bodySites(in: Parser.parse(source: developer)).contains { $0.isRouted }
            || developer.contains(routeOpen)
    }

    // MARK: - The in-file fallback block

    /// Append the PATCH-ROUTE block (the file must already have any previous one stripped).
    /// Always exactly `source + "\n" + block`, so stripping that suffix restores `source`
    /// byte-for-byte whether or not it ended with a newline.
    public static func appendingRouteFallback(to source: String) -> String {
        source + "\n" + routeFallbackBlock
    }

    /// Remove a PATCH-ROUTE block. When it is the file's suffix (where prepare always puts it)
    /// the removal is byte-exact (`source + "\n" + block` → `source`); a block that ended up
    /// elsewhere is removed with the same whitespace accounting as the other generated blocks.
    /// A BEGIN with no END is left alone.
    public static func stripRouteFallbackBlock(from source: String) -> String {
        guard let edit = routeFallbackBlockEdit(in: source) else { return source }
        return apply([edit], to: source)
    }

    /// The single edit that removes the PATCH-ROUTE block from `source` (see
    /// `stripRouteFallbackBlock`), as a UTF-8 byte-range replacement.
    static func routeFallbackBlockEdit(in source: String) -> TextEdit? {
        guard source.contains(routeFallbackBeginMarker) else { return nil }
        let bytes = Array(source.utf8)
        let suffix = Array(("\n" + routeFallbackBlock).utf8)
        if bytes.count >= suffix.count, Array(bytes[(bytes.count - suffix.count)...]) == suffix {
            return TextEdit((bytes.count - suffix.count)..<bytes.count, "")
        }
        guard let begin = source.range(of: routeFallbackBeginMarker),
              let end = source.range(of: routeFallbackEndMarker, range: begin.upperBound..<source.endIndex) else {
            return nil
        }
        var idx = end.upperBound
        if idx < source.endIndex, source[idx] == "\n" { idx = source.index(after: idx) }
        var headEnd = begin.lowerBound
        while headEnd > source.startIndex {
            let prev = source.index(before: headEnd)
            guard source[prev] == "\n" || source[prev] == " " else { break }
            headEnd = prev
        }
        let lower = source.utf8.distance(from: source.startIndex, to: headEnd)
        let upper = source.utf8.distance(from: source.startIndex, to: idx)
        return TextEdit(lower..<upper, "\n")
    }

    /// Ensure `source` carries exactly one PATCH-ROUTE block iff it has a routed body (the block
    /// goes last, after any other generated block).
    public static func normalizingRouteFallback(_ source: String) -> String {
        let stripped = stripRouteFallbackBlock(from: source)
        return hasRoutedBody(stripped) ? appendingRouteFallback(to: stripped) : stripped
    }

    /// The prepare result's modified files: every scanned file's working text (or its original,
    /// when prepare didn't touch it) with its PATCH-ROUTE fallback block normalized, keeping only
    /// files whose final text differs from what is on disk — a re-run on a prepared project
    /// reports no edits.
    static func finalizedModifiedFiles(_ parsed: [(file: SourceFile, tree: SourceFileSyntax)],
                                       _ fileText: [URL: String]) -> [(url: URL, text: String)] {
        parsed.compactMap { (file, _) in
            let working = fileText[file.url] ?? file.text
            let final = (fileText[file.url] == nil && !file.text.contains(routeMethodName))
                ? working : normalizingRouteFallback(working)
            return final == file.text ? nil : (file.url, final)
        }
    }

    // MARK: - Fingerprint canonical form

    /// The LEGACY prepared text of `source` for native-shell hashing: the PATCH-ROUTE block is
    /// removed and every routed body is unwrapped and given the `dynamic ` modifier the old
    /// `dynamic`-based prepare inserted at the `var` keyword. The shell hash of a project
    /// prepared by this CLI is therefore byte-identical to one prepared by an older CLI (the
    /// OTA modules are compatible with both: both thunk kinds call the same SDK entry point).
    /// `mapOffset` maps a UTF-8 offset in `source` to the canonical text (for byte ranges the
    /// engine computed on the routed file). Line numbers are unchanged. nil when `source` has
    /// no routing to canonicalize.
    public static func legacyCanonicalForm(_ source: String) -> (text: String, mapOffset: (Int) -> Int)? {
        guard source.contains(routeMethodName) else { return nil }
        var edits: [TextEdit] = []
        if let block = routeFallbackBlockEdit(in: source) { edits.append(block) }
        // The block itself is a `fileprivate extension View`, never a `var body` site.
        for s in bodySites(in: Parser.parse(source: source)) where s.isRouted {
            edits += (s.routeRanges ?? []).map { TextEdit($0, "") }
            if !s.isDynamic { edits.append(TextEdit(s.varOffset..<s.varOffset, "dynamic ")) }
        }
        guard !edits.isEmpty else { return nil }
        let text = apply(edits, to: source)
        let sorted = edits.sorted { $0.range.lowerBound < $1.range.lowerBound }
        let map: (Int) -> Int = { offset in
            var delta = 0
            for e in sorted {
                if e.range.lowerBound > offset { break }
                if e.range.isEmpty {
                    // An insertion AT `offset` precedes the byte there.
                    delta += e.replacement.utf8.count
                } else if e.range.upperBound <= offset {
                    delta += e.replacement.utf8.count - e.range.count
                } else {
                    // Inside a removed range (never an engine range) — clamp to its start.
                    return e.range.lowerBound + delta
                }
            }
            return offset + delta
        }
        return (text, map)
    }
}

// MARK: - Collector

final class BodySiteCollector: SyntaxVisitor {
    private var typeStack: [String] = []
    private var ifConfigDepth = 0
    private(set) var sites: [ThunkGenerator.BodySite] = []

    init() { super.init(viewMode: .sourceAccurate) }

    /// `var body: some View` (and ONLY `some View` — never `some Scene` /
    /// `some Commands` / `some ToolbarContent` / `some WidgetConfiguration`).
    static func isBodySomeView(_ node: VariableDeclSyntax) -> Bool {
        guard node.bindings.count == 1, let b = node.bindings.first,
              b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text == "body",
              let t = b.typeAnnotation?.type else { return false }
        return t.trimmedDescription == "some View"
    }

    override func visit(_ node: IfConfigDeclSyntax) -> SyntaxVisitorContinueKind { ifConfigDepth += 1; return .visitChildren }
    override func visitPost(_ node: IfConfigDeclSyntax) { ifConfigDepth -= 1 }
    override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind { typeStack.append(node.name.text); return .visitChildren }
    override func visitPost(_ node: StructDeclSyntax) { typeStack.removeLast() }
    override func visit(_ node: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
        typeStack.append(ThunkGenerator.baseTypeName(node.extendedType)); return .visitChildren
    }
    override func visitPost(_ node: ExtensionDeclSyntax) { typeStack.removeLast() }
    override func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind { typeStack.append(node.name.text); return .visitChildren }
    override func visitPost(_ node: EnumDeclSyntax) { typeStack.removeLast() }
    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind { typeStack.append(node.name.text); return .visitChildren }
    override func visitPost(_ node: ClassDeclSyntax) { typeStack.removeLast() }
    override func visit(_ node: ActorDeclSyntax) -> SyntaxVisitorContinueKind { typeStack.append(node.name.text); return .visitChildren }
    override func visitPost(_ node: ActorDeclSyntax) { typeStack.removeLast() }
    // A `body` inside a function/closure is a local, never a view body.
    override func visit(_ node: FunctionDeclSyntax) -> SyntaxVisitorContinueKind { .skipChildren }
    override func visit(_ node: ClosureExprSyntax) -> SyntaxVisitorContinueKind { .skipChildren }

    override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
        guard ifConfigDepth == 0, let type = typeStack.last,
              Self.isBodySomeView(node), let binding = node.bindings.first,
              let accessors = binding.accessorBlock else { return .skipChildren }
        var site = ThunkGenerator.BodySite(
            type: type, varOffset: node.bindingSpecifier.positionAfterSkippingLeadingTrivia.utf8Offset)
        if let dyn = node.modifiers.first(where: { $0.name.tokenKind == .keyword(.dynamic) }) {
            let start = dyn.positionAfterSkippingLeadingTrivia.utf8Offset
            var end = dyn.name.endPositionBeforeTrailingTrivia.utf8Offset
            // Exactly the one space legacy prepare added (never a newline / comment).
            if dyn.name.trailingTrivia.description.hasPrefix(" ") { end += 1 }
            site.dynamicRange = start..<end
        }
        // The getter's braces + statements: the shorthand `{ … }` or an explicit `get { … }`.
        let braces: (left: TokenSyntax, right: TokenSyntax, items: CodeBlockItemListSyntax)?
        switch accessors.accessors {
        case .getter(let items):
            braces = (accessors.leftBrace, accessors.rightBrace, items)
        case .accessors(let list):
            if list.count == 1, let get = list.first, get.accessorSpecifier.tokenKind == .keyword(.get),
               let body = get.body {
                braces = (body.leftBrace, body.rightBrace, body.statements)
            } else {
                braces = nil
            }
        }
        guard let braces, braces.left.presence == .present, braces.right.presence == .present else {
            sites.append(site); return .skipChildren
        }
        if let closure = ThunkGenerator.routeClosure(of: braces.items) {
            // Removing [getter `{` … closure `{`] and [closure `}` … getter `}`] restores the
            // original getter; for prepare's canonical text that is exactly `routeOpen`/`routeClose`.
            let openStart = braces.left.endPositionBeforeTrailingTrivia.utf8Offset
            let openEnd = closure.leftBrace.endPositionBeforeTrailingTrivia.utf8Offset
            let closeStart = closure.rightBrace.positionAfterSkippingLeadingTrivia.utf8Offset
            let closeEnd = braces.right.positionAfterSkippingLeadingTrivia.utf8Offset
            if openStart < openEnd, closeStart < closeEnd {
                site.routeRanges = [openStart..<openEnd, closeStart..<closeEnd]
            }
        } else if !braces.items.isEmpty {
            site.openInsertOffset = braces.left.endPositionBeforeTrailingTrivia.utf8Offset
            site.closeInsertOffset = braces.right.positionAfterSkippingLeadingTrivia.utf8Offset
        }
        sites.append(site)
        return .skipChildren
    }
}
