// SPDX-License-Identifier: Apache-2.0

import Foundation

/// Generates the **C-header import ABI** for Foundation host bridges used by the
/// Embedded-Swift (T0) tier.
///
/// ## Why a C header and not `@_extern(wasm)`
/// The proven module-size research (`research/module-size/shell-foundation/`)
/// found that Swift's `@_extern(wasm, module:..., name:...)` in **embedded** mode
/// emits a *mangled, non-flat* import ABI that WasmKit 0.2.2 **rejects**. The fix,
/// validated end-to-end (an embedded patch with no Foundation calling host Decimal/
/// JSON/Date ran correctly on WasmKit at 58 KB), is to declare the imports in a
/// **C header** with Clang's wasm attributes:
///
/// ```c
/// #define WASM_IMPORT(mod,nm) __attribute__((import_module(mod), import_name(nm)))
/// WASM_IMPORT("patch_host","decimal_op")
/// int64_t host_decimal_op(int32_t op, int64_t a, int64_t b, int32_t scale);
/// ```
///
/// Clang produces a **clean flat WASM ABI** — exactly the listed scalar params/
/// result, with no hidden Swift trailing args. The embedded module links a tiny
/// SwiftPM **C target** carrying this header, and the Swift fragment code calls
/// `host_decimal_op(...)` etc. directly. The native shell satisfies the imports
/// with its real Foundation via `PatchSDK.FoundationBridge`
/// (`patch_host.decimal_op` / `json_get_i64` / `now_unix_millis`).
///
/// The module namespace is **"patch_host"** and the import names match
/// `PatchSDK.FoundationBridge` exactly, so a CLI-built T0 module instantiates
/// against the SDK's default bridges with no extra wiring.
public struct CHeaderBridge {
    public init() {}

    /// The fixed module namespace the imports live in (matches `FoundationBridge`).
    public static let importModule = "patch_host"

    /// One generated artifact (a file to write into the embedded compile package).
    public struct File: Sendable, Equatable {
        /// Relative path inside the SwiftPM package (e.g. `Sources/CHost/include/chost.h`).
        public let relativePath: String
        public let contents: String
        public init(relativePath: String, contents: String) {
            self.relativePath = relativePath
            self.contents = contents
        }
    }

    /// C-target name the embedded Swift target depends on. The Swift fragments
    /// `import CHost` to see the flat host-import declarations.
    public static let cTargetName = "CHost"

    /// The host-import C function names the guest can call, paired with the
    /// `patch_host.*` import they bind to. (Source of truth for both the header
    /// and the embedded-fragment codegen.)
    public static let hostFunctions: [(swiftCallable: String, importName: String)] = [
        ("host_decimal_op", "decimal_op"),
        ("host_json_get_i64", "json_get_i64"),
        ("host_now_unix_millis", "now_unix_millis"),
        // Expanded surface (research/foundation-bridges): typed JSON readers +
        // string-return formatter / regex / date bridges.
        ("host_json_get_string", "json_get_string"),
        ("host_json_get_f64", "json_get_f64"),
        ("host_json_get_bool", "json_get_bool"),
        // Value-type receiver/arg marshalling at T0: extract a NESTED JSON object
        // at a top-level key as its OWN JSON blob (packed string), so its scalar
        // fields can be re-read with the existing top-level json_get_* readers.
        ("host_json_get_subobject", "json_get_subobject"),
        ("host_number_format", "number_format"),
        ("host_regex_find", "regex_find"),
        ("host_regex_count", "regex_count"),
        ("host_date_format", "date_format"),
    ]

    /// The generated `chost.h` — the clean flat-ABI import declarations. This is
    /// also the contract the native shell implements (it documents the exact ABI).
    public func headerSource() -> String {
        """
        // Auto-generated by Patch — Foundation host-bridge import ABI (C header).
        // DO NOT EDIT. Compiled into the Embedded-Swift (T0) OTA module.
        //
        // Host imports declared via Clang's wasm import_module/import_name
        // attributes. These produce a CLEAN flat WASM ABI: exactly the listed
        // params/result, no hidden Swift trailing args (which `@_extern(wasm)`
        // would emit and WasmKit rejects). This is the ABI the native shell's
        // PatchSDK.FoundationBridge implements (module "\(Self.importModule)").
        #ifndef PATCH_CHOST_H
        #define PATCH_CHOST_H
        #include <stdint.h>

        #define WASM_IMPORT(mod,nm) __attribute__((import_module(mod), import_name(nm)))

        // Exact base-10 Decimal arithmetic in the native shell's real Foundation.
        // op: 0=mul 1=div 2=add 3=sub. Operands are integers the guest tracks at
        // its own fixed-point `scale`; result is rounded to an integer (half-up).
        WASM_IMPORT("\(Self.importModule)","decimal_op")
        int64_t host_decimal_op(int32_t op, int64_t a, int64_t b, int32_t scale);

        // Parse a JSON object in guest memory (real JSONSerialization) and return
        // the integer value of a top-level numeric field (0 if absent).
        WASM_IMPORT("\(Self.importModule)","json_get_i64")
        int64_t host_json_get_i64(const uint8_t* ptr, int32_t len,
                                  const uint8_t* key, int32_t keyLen);

        // Real native Date() as Unix epoch milliseconds.
        WASM_IMPORT("\(Self.importModule)","now_unix_millis")
        int64_t host_now_unix_millis(void);

        // --- Expanded surface (research/foundation-bridges) -------------------
        // Typed JSON readers (packed (ptr<<32)|len string result; 0 = absent/null).
        WASM_IMPORT("\(Self.importModule)","json_get_string")
        int64_t host_json_get_string(const uint8_t* ptr, int32_t len,
                                     const uint8_t* key, int32_t keyLen);
        // f64 returned by bit-pattern in an i64 (guest reinterprets the bits).
        WASM_IMPORT("\(Self.importModule)","json_get_f64")
        int64_t host_json_get_f64(const uint8_t* ptr, int32_t len,
                                  const uint8_t* key, int32_t keyLen);
        // tri-state bool: 1 true, 0 false, -1 absent/non-bool.
        WASM_IMPORT("\(Self.importModule)","json_get_bool")
        int32_t host_json_get_bool(const uint8_t* ptr, int32_t len,
                                   const uint8_t* key, int32_t keyLen);
        // Extract the nested JSON value at a top-level key, re-serialized as its OWN
        // JSON blob, returned as a packed (ptr<<32)|len string allocated in OUR
        // linear memory (the guest frees it). 0 = absent. Used to marshal a
        // VALUE-TYPE receiver/arg field-by-field at T0 (no in-guest Foundation).
        WASM_IMPORT("\(Self.importModule)","json_get_subobject")
        int64_t host_json_get_subobject(const uint8_t* ptr, int32_t len,
                                        const uint8_t* key, int32_t keyLen);

        // Number/currency formatting via the shell's real NumberFormatter.
        // style: 0=decimal 1=currency 2=percent. `valueBits` is the bit-pattern of
        // the Double to format; `locale` is a locale id (e.g. "en_US").
        WASM_IMPORT("\(Self.importModule)","number_format")
        int64_t host_number_format(int64_t valueBits, int32_t style, int32_t fractionDigits,
                                   const uint8_t* locale, int32_t localeLen);
        // Regex first-match substring (packed string), 0 if no match / bad pattern.
        WASM_IMPORT("\(Self.importModule)","regex_find")
        int64_t host_regex_find(const uint8_t* str, int32_t strLen,
                                const uint8_t* pat, int32_t patLen);
        // Regex match count.
        WASM_IMPORT("\(Self.importModule)","regex_count")
        int32_t host_regex_count(const uint8_t* str, int32_t strLen,
                                 const uint8_t* pat, int32_t patLen);
        // Format a Unix-millis instant with a DateFormatter pattern -> packed string.
        WASM_IMPORT("\(Self.importModule)","date_format")
        int64_t host_date_format(int64_t unixMillis, const uint8_t* fmt, int32_t fmtLen,
                                 const uint8_t* tz, int32_t tzLen);

        // ---- FUSION host-bridge ABI (composes with self-free / pure exports) -----
        // The FusionRewriter (Date/Calendar/Formatter/regex builders) rewrites a
        // canonical native builder in a pure/self-free body to one of these flat
        // imports + its Swift shim (emitted into _PatchFusionShims.swift). Declaring
        // the import prototypes HERE (the always-present CHost target) lets that shim
        // resolve in the DEFAULT compile path — the exact join that lets
        // `SettingsScreen.relativeString` (`RelativeDateTimeFormatter`, absent from
        // WASM-corelib Foundation) ship at the Foundation tier instead of demoting.
        // These declare distinct C symbol names (`patch_*`) but bind the SAME
        // `patch_host.*` imports the SDK already serves (a duplicate (module,name)
        // with a different C prototype name is accepted by clang/wasm-ld — proven).
        // All harmless undefined imports under `--allow-undefined`; only the shims
        // for the bridges that actually fire are emitted, so unused imports never
        // appear in a real module.
        \(fusionImportDecls())

        #endif
        """
    }

    /// The fusion-bridge flat host-import declarations, deduped by C function NAME
    /// across `FusionRewriter.allBridges`. A bridge's `cDecl` may declare more than
    /// one `WASM_IMPORT(...)`; each is kept once (keyed by its C prototype name) so
    /// the combined CHost header never repeats a C symbol. Re-uses the FusionRewriter
    /// as the single source of truth for the (module,name) + prototype.
    func fusionImportDecls() -> String {
        var out: [String] = []
        var seenNames = Set<String>()
        // Match the C function name in a prototype line: `<ret> <name>(`.
        let nameRE = try? NSRegularExpression(
            pattern: #"\b([A-Za-z_][A-Za-z0-9_]*)\s*\("#)
        for bridge in FusionRewriter.allBridges {
            for (_, decl) in FusionRewriter.splitImportDecls(bridge.cDecl) {
                // The C function name is the last identifier immediately before `(`
                // in the prototype (after the WASM_IMPORT attribute line).
                let proto = decl.split(separator: "\n").map(String.init)
                    .first(where: { !$0.contains("WASM_IMPORT") && $0.contains("(") }) ?? decl
                let ns = proto as NSString
                guard let nameRE,
                      let m = nameRE.firstMatch(in: proto, range: NSRange(location: 0, length: ns.length)),
                      m.numberOfRanges >= 2 else { continue }
                let cName = ns.substring(with: m.range(at: 1))
                guard seenNames.insert(cName).inserted else { continue }
                out.append(decl)
            }
        }
        return out.joined(separator: "\n\n")
    }

    /// The C shim translation unit. A single `#include` so SwiftPM compiles the
    /// C target (a header-only target would produce no object and the import
    /// declarations would not be emitted).
    public func shimSource() -> String {
        """
        // Auto-generated by Patch — C shim for the Foundation host-bridge header.
        #include "include/chost.h"
        """
    }

    /// A small Swift convenience layer over the raw C imports, giving the
    /// generated fragments ergonomic, documented entry points. `import CHost`
    /// exposes the flat C functions; this wraps them with op-code constants and a
    /// JSON helper that handles the (ptr,len) marshalling the host expects.
    public func swiftBridgeSource() -> String {
        """
        // Auto-generated by Patch — Swift wrappers over the Foundation host bridge.
        // DO NOT EDIT. These call the flat C-header imports (module "\(Self.importModule)");
        // the native shell satisfies them via PatchSDK.FoundationBridge.
        import CHost

        // decimal_op op codes (mirror PatchSDK.FoundationBridge.Op).
        @usableFromInline let PATCH_DECIMAL_MUL: Int32 = 0
        @usableFromInline let PATCH_DECIMAL_DIV: Int32 = 1
        @usableFromInline let PATCH_DECIMAL_ADD: Int32 = 2
        @usableFromInline let PATCH_DECIMAL_SUB: Int32 = 3
        @usableFromInline let PATCH_DECIMAL_DIV_FLOOR: Int32 = 4  // truncate toward zero

        /// Exact base-10 Decimal arithmetic via the native shell's Foundation.
        /// op: 0=mul 1=div 2=add 3=sub. Operands are integers at the guest's
        /// chosen fixed-point `scale`; the result is rounded to an integer.
        @inlinable func patchDecimalOp(_ op: Int32, _ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(op, a, b, scale)
        }

        @inlinable func patchDecimalMul(_ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(PATCH_DECIMAL_MUL, a, b, scale)
        }
        @inlinable func patchDecimalDiv(_ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(PATCH_DECIMAL_DIV, a, b, scale)
        }
        @inlinable func patchDecimalAdd(_ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(PATCH_DECIMAL_ADD, a, b, scale)
        }
        @inlinable func patchDecimalSub(_ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(PATCH_DECIMAL_SUB, a, b, scale)
        }
        /// Division truncating toward zero — the standard money policy for taxes
        /// and fees (matches integer-cents `(a*rate)/denom`), via real Decimal.
        @inlinable func patchDecimalDivFloor(_ a: Int64, _ b: Int64, scale: Int32 = 2) -> Int64 {
            host_decimal_op(PATCH_DECIMAL_DIV_FLOOR, a, b, scale)
        }

        /// Read a top-level integer JSON field. `json` and `key` are read from
        /// guest linear memory by the host; we pass their (ptr,len).
        @inlinable func patchJSONGetI64(_ json: [UInt8], _ key: String) -> Int64 {
            let keyBytes = Array(key.utf8)
            return json.withUnsafeBufferPointer { jp in
                keyBytes.withUnsafeBufferPointer { kp in
                    host_json_get_i64(jp.baseAddress, Int32(jp.count), kp.baseAddress, Int32(kp.count))
                }
            }
        }

        /// Real native `Date()` as Unix epoch milliseconds.
        @inlinable func patchNowUnixMillis() -> Int64 { host_now_unix_millis() }

        // --- Expanded surface (research/foundation-bridges) -------------------
        // String-return path: the host allocated a buffer in OUR linear memory (via
        // our exported patch_malloc) and wrote UTF-8 bytes; we read them with
        // String(decoding:as:) (embedded-safe) and free the host buffer. A packed
        // result of 0 means absent/empty.
        @inlinable func _patchUnpack(_ packed: Int64) -> (ptr: Int, len: Int) {
            (Int((packed >> 32) & 0xffff_ffff), Int(packed & 0xffff_ffff))
        }
        @inlinable func _readPackedString(_ packed: Int64) -> String {
            let (ptr, len) = _patchUnpack(packed)
            if ptr == 0 || len == 0 { return "" }
            guard let base = UnsafePointer<UInt8>(bitPattern: ptr) else { return "" }
            let s = String(decoding: UnsafeBufferPointer(start: base, count: len), as: UTF8.self)
            UnsafeMutableRawPointer(bitPattern: ptr)?.deallocate()   // free host buffer
            return s
        }

        /// Number/currency/percent formatting via the shell's real NumberFormatter
        /// (locale-correct via the shell's ICU). style: 0=decimal 1=currency 2=percent.
        @inlinable func patchNumberFormat(_ value: Double, style: Int32, fractionDigits: Int32, locale: String) -> String {
            let bits = Int64(bitPattern: value.bitPattern)
            let loc = Array(locale.utf8)
            let packed = loc.withUnsafeBufferPointer { lp in
                host_number_format(bits, style, fractionDigits, lp.baseAddress, Int32(lp.count))
            }
            return _readPackedString(packed)
        }

        /// First regex match substring (empty string if none / bad pattern).
        @inlinable func patchRegexFind(_ str: String, _ pat: String) -> String {
            let s = Array(str.utf8), p = Array(pat.utf8)
            let packed = s.withUnsafeBufferPointer { sp in
                p.withUnsafeBufferPointer { pp in
                    host_regex_find(sp.baseAddress, Int32(sp.count), pp.baseAddress, Int32(pp.count))
                }
            }
            return _readPackedString(packed)
        }

        /// Regex match count.
        @inlinable func patchRegexCount(_ str: String, _ pat: String) -> Int32 {
            let s = Array(str.utf8), p = Array(pat.utf8)
            return s.withUnsafeBufferPointer { sp in
                p.withUnsafeBufferPointer { pp in
                    host_regex_count(sp.baseAddress, Int32(sp.count), pp.baseAddress, Int32(pp.count))
                }
            }
        }

        /// Format a Unix-millis instant with a DateFormatter pattern (e.g. "yyyy-MM-dd").
        @inlinable func patchDateFormat(_ unixMillis: Int64, _ fmt: String, _ tz: String = "") -> String {
            let f = Array(fmt.utf8), z = Array(tz.utf8)
            let packed = f.withUnsafeBufferPointer { fp in
                z.withUnsafeBufferPointer { zp in
                    host_date_format(unixMillis, fp.baseAddress, Int32(fp.count), zp.baseAddress, Int32(zp.count))
                }
            }
            return _readPackedString(packed)
        }

        /// Read a top-level String JSON field (empty string if absent / non-string).
        @inlinable func patchJSONGetString(_ json: [UInt8], _ key: String) -> String {
            let k = Array(key.utf8)
            let packed = json.withUnsafeBufferPointer { jp in
                k.withUnsafeBufferPointer { kp in
                    host_json_get_string(jp.baseAddress, Int32(jp.count), kp.baseAddress, Int32(kp.count))
                }
            }
            return _readPackedString(packed)
        }

        /// Read a top-level numeric JSON field as a Double.
        @inlinable func patchJSONGetF64(_ json: [UInt8], _ key: String) -> Double {
            let k = Array(key.utf8)
            let bits = json.withUnsafeBufferPointer { jp in
                k.withUnsafeBufferPointer { kp in
                    host_json_get_f64(jp.baseAddress, Int32(jp.count), kp.baseAddress, Int32(kp.count))
                }
            }
            return Double(bitPattern: UInt64(bitPattern: bits))
        }

        /// Read a top-level Bool JSON field (nil = absent / non-bool).
        @inlinable func patchJSONGetBool(_ json: [UInt8], _ key: String) -> Bool? {
            let k = Array(key.utf8)
            let r = json.withUnsafeBufferPointer { jp in
                k.withUnsafeBufferPointer { kp in
                    host_json_get_bool(jp.baseAddress, Int32(jp.count), kp.baseAddress, Int32(kp.count))
                }
            }
            return r < 0 ? nil : (r != 0)
        }

        /// Extract the nested JSON object at `key` as its OWN JSON blob bytes (empty
        /// when absent). The host re-serializes the sub-object into OUR linear memory
        /// (allocated via patch_malloc); we copy it out and free the host buffer.
        /// This lets a VALUE-TYPE receiver/arg be marshalled field-by-field at T0:
        /// read the sub-blob, then read each scalar stored field from it with the
        /// existing top-level json_get_* readers — no in-guest Foundation/Codable.
        @inlinable func patchJSONGetSubobject(_ json: [UInt8], _ key: String) -> [UInt8] {
            let k = Array(key.utf8)
            let packed = json.withUnsafeBufferPointer { jp in
                k.withUnsafeBufferPointer { kp in
                    host_json_get_subobject(jp.baseAddress, Int32(jp.count), kp.baseAddress, Int32(kp.count))
                }
            }
            let (ptr, len) = _patchUnpack(packed)
            if ptr == 0 || len == 0 { return [] }
            guard let base = UnsafePointer<UInt8>(bitPattern: ptr) else { return [] }
            let bytes = Array(UnsafeBufferPointer(start: base, count: len))
            UnsafeMutableRawPointer(bitPattern: ptr)?.deallocate()   // free host buffer
            return bytes
        }
        """
    }

    /// All files for the C-bridge target, ready to write into the embedded
    /// compile package: `Sources/CHost/include/chost.h`, `Sources/CHost/shim.c`,
    /// and `Sources/<swiftTarget>/_patch_host_bridge.swift`.
    public func files(swiftTargetName: String = "PatchWasm") -> [File] {
        [
            File(relativePath: "Sources/\(Self.cTargetName)/include/chost.h", contents: headerSource()),
            File(relativePath: "Sources/\(Self.cTargetName)/shim.c", contents: shimSource()),
            File(relativePath: "Sources/\(swiftTargetName)/_patch_host_bridge.swift", contents: swiftBridgeSource()),
        ]
    }
}
