// SPDX-License-Identifier: Apache-2.0

// PatchAccessForwarding.swift — reach a view's `private` members from the SEPARATE generated
// thunk file WITHOUT putting the thunk in the developer's source file.
// =============================================================================================
// THE PROBLEM. A view's generated thunk helpers (`__patchSlots()`/`__patchTokens()`/…) evaluate
// native slot/token/action closures over `self`. When those closures read a `private` member
// (`header`, `$isOn`, `row(_:)`, a `private struct Row: View`) Swift's FILE-SCOPED access control
// forces the helpers into the view's own file — historically a large PATCH-THUNKS block per file
// (thousands of generated lines across files a team edits daily).
//
// THE FIX (the "accessor shim", proven with swiftc — see experiments/patch-access-macro/NOTES.md).
// The view's file gets ONE compact, sorted, clearly-marked extension of internal FORWARDERS — one
// per private member the thunk actually uses — and EVERYTHING ELSE (replacement, slots, tokens,
// row/action/effect/callback slots) moves to `Patch/Generated/`, with its private references
// rewritten to the forwarders:
//
//     // PATCH-ACCESS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)
//     extension MixView {
//         var __patch_header: some View { header }
//         var __patchProj_isOn: Binding<Bool> { $isOn }
//         func __patch_row(_ p0: Track) -> some View { row(p0) }
//     }
//     // PATCH-ACCESS-END
//
// The forwarder set is a function of WHICH private members the thunk uses (not of the body's
// content), sorted, so it only changes when that set changes — a body edit leaves it byte-stable.
//
// BUILD-SAFE BY CONSTRUCTION. Forwarding is all-or-nothing per view: every private reference in
// the rendered helper text must (a) resolve unambiguously to a cataloged member of the view
// declared in the view's own file, (b) not be lexically shadowed, and (c) have a SPELLABLE type
// (explicit annotation, a literal/constructor initializer, or a known `@Environment` key) that
// mentions no file-private type. Anything else → the view keeps the legacy same-file block
// (never a guess), and the blocking member is reported by name with the reason.

import Foundation
import SwiftSyntax
import SwiftParser

public enum PatchAccessForwarding {

    // MARK: - Markers

    public static let beginMarker = "// PATCH-ACCESS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)"
    public static let endMarker = "// PATCH-ACCESS-END"

    /// Value / computed / method forwarder prefix (`header` → `__patch_header`).
    static let valuePrefix = "__patch_"
    /// Property-wrapper PROJECTION forwarder prefix (`$isOn` → `__patchProj_isOn`).
    static let projectionPrefix = "__patchProj_"
    /// Private View-type FACTORY prefix (`MixTrackRow(track:)` → `__patchMake_MixTrackRow(track:)`).
    static let factoryPrefix = "__patchMake_"

    // MARK: - Catalog

    /// A `private`/`fileprivate` stored or computed property of the view.
    struct VariableInfo {
        let name: String
        let isStatic: Bool
        /// The wrapper attribute name (`State`, `Binding`, `Environment`, …), if any.
        let wrapper: String?
        /// The spelled value type, or nil when it can't be spelled (with `unspellableReason`).
        let typeText: String?
        let unspellableReason: String?
        /// Declared with `let` (never settable).
        let isLet: Bool
    }

    /// Everything a forwarder may reach for ONE view, gathered from the view's declaring file.
    public struct Catalog {
        let viewName: String
        var vars: [String: VariableInfo] = [:]
        var funcs: [String: [FunctionDeclSyntax]] = [:]
        /// `private`/`fileprivate` View structs reachable from the view's file by simple name
        /// (top-level in the file, or nested in the view).
        var privateViewTypes: [String: StructDeclSyntax] = [:]
        /// Every inaccessible type name declared anywhere in the file (signature checks).
        var privateTypeNames: Set<String> = []
        /// Every private member name of the view (bare + `$`), INCLUDING ones declared outside the
        /// declaring file — a reference to one we didn't catalog is a hard fallback.
        var allPrivateMemberNames: Set<String> = []
        /// `private`/`fileprivate` member names of OTHER types (and their extensions) declared in the
        /// file — reachable from the legacy same-file block via `other.name`, NOT from Generated/.
        var otherTypePrivateMemberNames: Set<String> = []
        /// Top-level `private`/`fileprivate` functions/variables in the file.
        var filePrivateGlobals: Set<String> = []
        /// Every type name DECLARED in the file (any nesting, any access).
        var fileDeclaredTypeNames: Set<String> = []
        /// Every member of the view (any access) → its spelled/inferred type's base name, used to
        /// prove a `member.name` access targets a type declared in ANOTHER file.
        var memberBaseTypes: [String: String] = [:]
    }

    static func isPrivateModifier(_ mods: DeclModifierListSyntax) -> Bool {
        mods.contains { $0.name.tokenKind == .keyword(.private) || $0.name.tokenKind == .keyword(.fileprivate) }
    }

    /// Build the catalog for `viewName` from its DECLARING file's tree. `allPrivateMemberNames` is
    /// the caller's project-wide private-member set for the view (members declared in extensions in
    /// other files are file-scoped THERE, so they're deliberately not forwardable from here).
    public static func catalog(viewName: String, declaringTree tree: SourceFileSyntax,
                               allPrivateMemberNames: Set<String>,
                               knownSelfTypedStatics: Set<String> = []) -> Catalog {
        var c = Catalog(viewName: viewName)
        c.allPrivateMemberNames = allPrivateMemberNames

        // Every inaccessible type name in the file (any nesting depth).
        final class PrivateTypeScanner: SyntaxVisitor {
            var names = Set<String>()
            var all = Set<String>()
            // Enclosing `private extension X { … }` / private types: a type nested in one is
            // file-private too (real app: NewsApp's `private extension FavoritesView { struct
            // Constants }`, referenced as `Constants.title` from a slot).
            var privateScope: [Bool] = []
            init() { super.init(viewMode: .sourceAccurate) }
            func note(_ mods: DeclModifierListSyntax, _ name: String) {
                all.insert(name)
                if PatchAccessForwarding.isPrivateModifier(mods) || privateScope.contains(true) { names.insert(name) }
                privateScope.append(PatchAccessForwarding.isPrivateModifier(mods))
            }
            override func visit(_ n: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
                privateScope.append(PatchAccessForwarding.isPrivateModifier(n.modifiers)); return .visitChildren
            }
            override func visitPost(_ n: ExtensionDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: StructDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: StructDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: ClassDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: ClassDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: EnumDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: EnumDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: ActorDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: ActorDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: ProtocolDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: ProtocolDeclSyntax) { privateScope.removeLast() }
            override func visit(_ n: TypeAliasDeclSyntax) -> SyntaxVisitorContinueKind { note(n.modifiers, n.name.text); return .visitChildren }
            override func visitPost(_ n: TypeAliasDeclSyntax) { privateScope.removeLast() }
        }
        let pts = PrivateTypeScanner()
        pts.walk(tree)
        c.privateTypeNames = pts.names
        c.fileDeclaredTypeNames = pts.all

        // Private members of every OTHER type / extension in the file (any nesting), and file-private
        // top-level globals — a thunk reading one can't move out of the file.
        final class OtherPrivateMemberScanner: SyntaxVisitor {
            let viewName: String
            var names = Set<String>()
            init(viewName: String) { self.viewName = viewName; super.init(viewMode: .sourceAccurate) }
            func absorb(_ members: MemberBlockItemListSyntax, _ allPrivate: Bool) {
                for m in members {
                    if let v = m.decl.as(VariableDeclSyntax.self), allPrivate || PatchAccessForwarding.isPrivateModifier(v.modifiers) {
                        for b in v.bindings { if let n = b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text { names.insert(n) } }
                    } else if let f = m.decl.as(FunctionDeclSyntax.self), allPrivate || PatchAccessForwarding.isPrivateModifier(f.modifiers) {
                        names.insert(f.name.text)
                    }
                }
            }
            override func visit(_ n: StructDeclSyntax) -> SyntaxVisitorContinueKind {
                if n.name.text != viewName { absorb(n.memberBlock.members, false) }
                return .visitChildren
            }
            override func visit(_ n: ClassDeclSyntax) -> SyntaxVisitorContinueKind { absorb(n.memberBlock.members, false); return .visitChildren }
            override func visit(_ n: EnumDeclSyntax) -> SyntaxVisitorContinueKind { absorb(n.memberBlock.members, false); return .visitChildren }
            override func visit(_ n: ActorDeclSyntax) -> SyntaxVisitorContinueKind { absorb(n.memberBlock.members, false); return .visitChildren }
            override func visit(_ n: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
                if ThunkGenerator.baseTypeName(n.extendedType) != viewName {
                    absorb(n.memberBlock.members, PatchAccessForwarding.isPrivateModifier(n.modifiers))
                }
                return .visitChildren
            }
        }
        let ops = OtherPrivateMemberScanner(viewName: viewName)
        ops.walk(tree)
        c.otherTypePrivateMemberNames = ops.names
        for stmt in tree.statements {
            if let v = stmt.item.as(VariableDeclSyntax.self), isPrivateModifier(v.modifiers) {
                for b in v.bindings { if let n = b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text { c.filePrivateGlobals.insert(n) } }
            } else if let f = stmt.item.as(FunctionDeclSyntax.self), isPrivateModifier(f.modifiers) {
                c.filePrivateGlobals.insert(f.name.text)
            }
        }

        func isView(_ s: StructDeclSyntax) -> Bool {
            s.inheritanceClause?.inheritedTypes.contains { $0.type.trimmedDescription == "View" } ?? false
        }
        func absorb(members: MemberBlockItemListSyntax, extensionIsPrivate: Bool) {
            for member in members {
                if let v = member.decl.as(VariableDeclSyntax.self) {
                    for info in variableInfos(v, known: knownSelfTypedStatics) {
                        if let t = info.typeText { c.memberBaseTypes[info.name] = baseName(ofType: t) }
                    }
                }
                if let v = member.decl.as(VariableDeclSyntax.self),
                   extensionIsPrivate || isPrivateModifier(v.modifiers) {
                    for info in variableInfos(v, known: knownSelfTypedStatics) { c.vars[info.name] = info }
                } else if let f = member.decl.as(FunctionDeclSyntax.self),
                          extensionIsPrivate || isPrivateModifier(f.modifiers) {
                    c.funcs[f.name.text, default: []].append(f)
                } else if let s = member.decl.as(StructDeclSyntax.self), isPrivateModifier(s.modifiers), isView(s) {
                    c.privateViewTypes[s.name.text] = s
                }
            }
        }
        for stmt in tree.statements {
            if let s = stmt.item.as(StructDeclSyntax.self) {
                if s.name.text == viewName {
                    absorb(members: s.memberBlock.members, extensionIsPrivate: false)
                } else if isPrivateModifier(s.modifiers), isView(s), s.genericParameterClause == nil {
                    c.privateViewTypes[s.name.text] = s
                }
            } else if let e = stmt.item.as(ExtensionDeclSyntax.self),
                      ThunkGenerator.baseTypeName(e.extendedType) == viewName {
                absorb(members: e.memberBlock.members, extensionIsPrivate: isPrivateModifier(e.modifiers))
            }
        }
        return c
    }

    // MARK: - Type spelling

    /// Well-known `@Environment(\.key)` value types — so the common `@Environment(\.dismiss)
    /// private var dismiss` (no annotation) is forwardable. Unknown keys → not spellable.
    static let environmentKeyTypes: [String: String] = [
        "dismiss": "DismissAction", "openURL": "OpenURLAction", "colorScheme": "ColorScheme",
        "scenePhase": "ScenePhase", "horizontalSizeClass": "UserInterfaceSizeClass?",
        "verticalSizeClass": "UserInterfaceSizeClass?", "dynamicTypeSize": "DynamicTypeSize",
        "locale": "Locale", "calendar": "Calendar", "timeZone": "TimeZone", "isEnabled": "Bool",
        "isSearching": "Bool", "isPresented": "Bool", "displayScale": "CGFloat",
        "layoutDirection": "LayoutDirection", "colorSchemeContrast": "ColorSchemeContrast",
        "accessibilityReduceMotion": "Bool", "accessibilityReduceTransparency": "Bool",
        "accessibilityDifferentiateWithoutColor": "Bool", "accessibilityVoiceOverEnabled": "Bool",
        "sizeCategory": "ContentSizeCategory", "undoManager": "UndoManager?",
        "presentationMode": "Binding<PresentationMode>", "editMode": "Binding<EditMode>?",
        "openWindow": "OpenWindowAction", "dismissSearch": "DismissSearchAction",
        "refresh": "RefreshAction?", "font": "Font?", "redactionReasons": "RedactionReasons",
        "legibilityWeight": "LegibilityWeight?", "managedObjectContext": "NSManagedObjectContext",
        "modelContext": "ModelContext", "requestReview": "RequestReviewAction",
        "purchase": "PurchaseAction", "supportsMultipleWindows": "Bool",
    ]

    /// `Optional<Foo>` / `Foo?` / `Foo!` / `Module.Foo<T>` → `Foo`.
    static func baseName(ofType t: String) -> String {
        var s = t.trimmingCharacters(in: .whitespaces)
        while s.hasSuffix("?") || s.hasSuffix("!") { s.removeLast() }
        if let lt = s.firstIndex(of: "<") { s = String(s[..<lt]) }
        return String(s.split(separator: ".").last ?? Substring(s))
    }

    /// SDK types whose lowercase static members are (overwhelmingly) of the type itself.
    static let sdkSelfTypedStaticBases: Set<String> = ["Color", "Font", "Date", "Locale", "Calendar", "TimeZone",
                                                       "Animation", "Edge", "Alignment", "HorizontalAlignment",
                                                       "VerticalAlignment", "UnitPoint", "ColorScheme", "CGPoint",
                                                       "CGSize", "CGRect", "EdgeInsets"]

    /// Project-wide `Type.member` pairs whose type is provably `Type`: enum cases, and static members
    /// annotated `Type`/`Self` or initialized with `Type(…)`/`Self(…)`/`.init(…)`.
    public static func selfTypedStaticMembers(trees: [SourceFileSyntax]) -> Set<String> {
        final class V: SyntaxVisitor {
            var out = Set<String>()
            var stack: [String] = []
            init() { super.init(viewMode: .sourceAccurate) }
            override func visit(_ n: EnumDeclSyntax) -> SyntaxVisitorContinueKind { stack.append(n.name.text); return .visitChildren }
            override func visitPost(_ n: EnumDeclSyntax) { stack.removeLast() }
            override func visit(_ n: StructDeclSyntax) -> SyntaxVisitorContinueKind { stack.append(n.name.text); return .visitChildren }
            override func visitPost(_ n: StructDeclSyntax) { stack.removeLast() }
            override func visit(_ n: ClassDeclSyntax) -> SyntaxVisitorContinueKind { stack.append(n.name.text); return .visitChildren }
            override func visitPost(_ n: ClassDeclSyntax) { stack.removeLast() }
            override func visit(_ n: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind { stack.append(PatchAccessForwarding.baseName(ofType: n.extendedType.trimmedDescription)); return .visitChildren }
            override func visitPost(_ n: ExtensionDeclSyntax) { stack.removeLast() }
            override func visit(_ n: EnumCaseDeclSyntax) -> SyntaxVisitorContinueKind {
                if let t = stack.last { for e in n.elements where e.parameterClause == nil { out.insert("\(t).\(e.name.text)") } }
                return .skipChildren
            }
            override func visit(_ n: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
                guard let t = stack.last, n.modifiers.contains(where: { $0.name.tokenKind == .keyword(.static) }) else { return .skipChildren }
                for b in n.bindings {
                    guard let name = b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text else { continue }
                    let ann = b.typeAnnotation?.type.trimmedDescription
                    let callee = b.initializer?.value.as(FunctionCallExprSyntax.self)?.calledExpression.trimmedDescription
                    if ann == t || ann == "Self" || (ann == nil && (callee == t || callee == "Self" || callee == ".init")) {
                        out.insert("\(t).\(name)")
                    }
                }
                return .skipChildren
            }
        }
        let v = V()
        for t in trees { v.walk(t) }
        return v.out
    }

    static func variableInfos(_ v: VariableDeclSyntax, known: Set<String> = []) -> [VariableInfo] {
        let isStatic = v.modifiers.contains { $0.name.tokenKind == .keyword(.static) || $0.name.tokenKind == .keyword(.class) }
        let isLet = v.bindingSpecifier.tokenKind == .keyword(.let)
        let wrapperAttr = v.attributes.compactMap { $0.as(AttributeSyntax.self) }.first
        let wrapper = wrapperAttr.map { ThunkGenerator.baseTypeName($0.attributeName) }
            .flatMap { ["ViewBuilder", "MainActor", "available", "objc", "Published", "discardableResult"].contains($0) ? nil : $0 }
        var out: [VariableInfo] = []
        for b in v.bindings {
            guard let name = b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text else { continue }
            var type: String? = b.typeAnnotation?.type.trimmedDescription
            var reason: String? = nil
            if type == nil, let w = wrapper, w == "Environment",
               let arg = wrapperAttr?.arguments?.as(LabeledExprListSyntax.self)?.first?.expression {
                if let kp = arg.as(KeyPathExprSyntax.self), kp.root == nil, kp.components.count == 1,
                   let comp = kp.components.first?.component.as(KeyPathPropertyComponentSyntax.self) {
                    type = environmentKeyTypes[comp.declName.baseName.text]
                    if type == nil { reason = "`@Environment(\\.\(comp.declName.baseName.text))` has no explicit type" }
                } else if let m = arg.as(MemberAccessExprSyntax.self), m.declName.baseName.text == "self",
                          let base = m.base {
                    type = base.trimmedDescription          // @Environment(Model.self)
                }
            } else if type == nil, let w = wrapper, w == "Namespace" {
                type = "Namespace.ID"
            } else if type == nil, let initExpr = b.initializer?.value {
                type = inferredType(of: initExpr, known: known)
                if type == nil { reason = "`\(name)` has no explicit type annotation" }
            } else if type == nil {
                reason = "`\(name)` has no explicit type annotation"
            }
            // `private var x: some P { … }` forwards as `some P`; a stored opaque type can't exist.
            out.append(VariableInfo(name: name, isStatic: isStatic, wrapper: wrapper,
                                    typeText: type, unspellableReason: type == nil ? (reason ?? "unspellable type") : nil,
                                    isLet: isLet))
        }
        return out
    }

    /// The type of a simple initializer expression, when it is unambiguous from syntax alone.
    static func inferredType(of e: ExprSyntax, known: Set<String> = []) -> String? {
        // `TypeName.member` where the member is provably of type `TypeName` (an enum case, …).
        if let m = e.as(MemberAccessExprSyntax.self), let base = m.base?.as(DeclReferenceExprSyntax.self),
           base.baseName.text.first?.isUppercase == true, m.declName.baseName.text.first?.isLowercase == true {
            let t = base.baseName.text
            if known.contains("\(t).\(m.declName.baseName.text)") || sdkSelfTypedStaticBases.contains(t) { return t }
            return nil
        }
        if e.is(BooleanLiteralExprSyntax.self) { return "Bool" }
        if e.is(IntegerLiteralExprSyntax.self) { return "Int" }
        if e.is(FloatLiteralExprSyntax.self) { return "Double" }
        if e.is(StringLiteralExprSyntax.self) { return "String" }
        if let p = e.as(PrefixOperatorExprSyntax.self), p.operator.text == "-" {
            return inferredType(of: p.expression).flatMap { $0 == "Int" || $0 == "Double" ? $0 : nil }
        }
        // `TypeName(…)` / `Module.TypeName(…)` — an uppercase callee is a type construction.
        if let call = e.as(FunctionCallExprSyntax.self), call.trailingClosure == nil {
            let callee = call.calledExpression.trimmedDescription
            let comps = callee.split(separator: ".")
            if !comps.isEmpty, comps.allSatisfy({ $0.first?.isUppercase == true && $0.allSatisfy { $0.isLetter || $0.isNumber || $0 == "_" } }) {
                return callee
            }
            // `[Item]()` / `[String: Int]()`
            if let arr = call.calledExpression.as(ArrayExprSyntax.self), arr.elements.count == 1 {
                return "[\(arr.elements.first!.expression.trimmedDescription)]"
            }
        }
        return nil
    }

    /// True when a spelled type text mentions a file-private type (or is otherwise unusable in an
    /// internal signature).
    static func typeMentionsPrivate(_ text: String, _ c: Catalog) -> Bool {
        let idents = text.split(whereSeparator: { !($0.isLetter || $0.isNumber || $0 == "_") }).map(String.init)
        return idents.contains { c.privateTypeNames.contains($0) || c.privateViewTypes[$0] != nil }
    }

    // MARK: - Reference rewrite

    /// The argument labels (and trailing-closure use) of one private-View-type construction site.
    struct CallShape: Hashable { let labels: [String]; let hasTrailingClosure: Bool }

    enum Usage: Hashable {
        case value(String)          // instance or static var
        case projection(String)     // $var
        case function(String)       // instance or static method
        case factory(String)        // private View type construction
    }

    public struct Forwarded {
        /// The rewritten helper-methods extension (goes into Patch/Generated/).
        public let rewrittenText: String
        /// The sorted forwarder declarations (go into the view's own file).
        public let forwarders: [String]
        /// The private member names forwarded (for reporting), sorted.
        public let members: [String]
    }

    /// Try to forward every private reference in `methodsExtension` (a rendered helper-methods
    /// extension for `catalog.viewName`). Returns the rewrite + forwarders, or the blocking members
    /// with a reason each (the caller then keeps the legacy same-file placement).
    public static func forward(methodsExtension: String, catalog c: Catalog)
        -> (forwarded: Forwarded?, blockers: [String: String]) {
        let tree = Parser.parse(source: methodsExtension)
        guard !tree.hasError else { return (nil, ["<thunk>": "generated helper text did not parse"]) }
        let scanner = ReferenceRewriteScanner(catalog: c)
        scanner.walk(tree)
        if !scanner.blockers.isEmpty { return (nil, scanner.blockers) }

        // Build forwarders for each usage.
        var decls: [String] = []
        var blockers: [String: String] = [:]
        for usage in scanner.usages.sorted(by: { "\($0)" < "\($1)" }) {
            switch forwarderDecls(for: usage, catalog: c, callSites: scanner.factoryCallSites) {
            case .success(let d): decls.append(contentsOf: d)
            case .failure(let f): blockers[f.member] = f.reason
            }
        }
        if !blockers.isEmpty { return (nil, blockers) }

        // Apply the edits (descending so offsets stay valid).
        var bytes = Array(methodsExtension.utf8)
        for edit in scanner.edits.sorted(by: { $0.range.lowerBound > $1.range.lowerBound }) {
            bytes.replaceSubrange(edit.range, with: Array(edit.replacement.utf8))
        }
        let rewritten = String(decoding: bytes, as: UTF8.self)
        guard ThunkGenerator.parses(rewritten) else {
            return (nil, ["<thunk>": "rewritten helper text did not parse"])
        }
        let members = Set(scanner.usages.map { u -> String in
            switch u {
            case .value(let n), .function(let n), .factory(let n): return n
            case .projection(let n): return "$" + n
            }
        }).sorted()
        return (Forwarded(rewrittenText: rewritten, forwarders: Array(Set(decls)).sorted(), members: members), [:])
    }

    struct ForwardFailure: Error { let member: String; let reason: String }

    static func forwarderDecls(for usage: Usage, catalog c: Catalog,
                               callSites: [String: [CallShape]] = [:]) -> Result<[String], ForwardFailure> {
        switch usage {
        case .value(let name):
            guard let v = c.vars[name] else { return .failure(.init(member: name, reason: "not a forwardable property")) }
            guard let t = v.typeText else { return .failure(.init(member: name, reason: v.unspellableReason ?? "unspellable type")) }
            if typeMentionsPrivate(t, c) {
                return .failure(.init(member: name, reason: "its type `\(t)` mentions a private type"))
            }
            let stat = v.isStatic ? "static " : ""
            let settable = !v.isLet && !v.isStatic
                && ["State", "Binding", "AppStorage", "SceneStorage", "FocusState"].contains(v.wrapper ?? "")
            if settable {
                return .success(["\(stat)var \(valuePrefix)\(name): \(t) { get { \(name) } nonmutating set { \(name) = newValue } }"])
            }
            return .success(["\(stat)var \(valuePrefix)\(name): \(t) { \(name) }"])
        case .projection(let name):
            guard let v = c.vars[name], !v.isStatic else { return .failure(.init(member: "$" + name, reason: "not a forwardable property wrapper")) }
            guard let t = v.typeText else { return .failure(.init(member: "$" + name, reason: v.unspellableReason ?? "unspellable type")) }
            if typeMentionsPrivate(t, c) {
                return .failure(.init(member: "$" + name, reason: "its type `\(t)` mentions a private type"))
            }
            let projected: String?
            switch v.wrapper ?? "" {
            case "State", "Binding", "AppStorage", "SceneStorage": projected = "Binding<\(t)>"
            case "FocusState": projected = "FocusState<\(t)>.Binding"
            case "StateObject", "ObservedObject": projected = "ObservedObject<\(t)>.Wrapper"
            case "EnvironmentObject": projected = "EnvironmentObject<\(t)>.Wrapper"
            case "Bindable": projected = "Bindable<\(t)>"
            case "GestureState": projected = "GestureState<\(t)>"
            default: projected = nil
            }
            guard let p = projected else {
                return .failure(.init(member: "$" + name, reason: "projection of `@\(v.wrapper ?? "?")` is not forwardable"))
            }
            return .success(["var \(projectionPrefix)\(name): \(p) { $\(name) }"])
        case .function(let name):
            guard let overloads = c.funcs[name], !overloads.isEmpty else {
                return .failure(.init(member: name, reason: "not a forwardable method"))
            }
            var out: [String] = []
            for f in overloads {
                switch functionForwarder(f, catalog: c) {
                case .success(let d): out.append(d)
                case .failure(let e): return .failure(e)
                }
            }
            return .success(out)
        case .factory(let typeName):
            guard let s = c.privateViewTypes[typeName] else {
                return .failure(.init(member: typeName, reason: "private type is not a forwardable View"))
            }
            return factoryForwarders(s, callSites: callSites[typeName] ?? [], catalog: c)
        }
    }

    /// `private func row(_ t: Track, compact: Bool = false) -> some View` →
    /// `func __patch_row(_ p0: Track, compact p1: Bool = false) -> some View { row(p0, compact: p1) }`.
    static func functionForwarder(_ f: FunctionDeclSyntax, catalog c: Catalog) -> Result<String, ForwardFailure> {
        let name = f.name.text
        func fail(_ r: String) -> Result<String, ForwardFailure> { .failure(.init(member: name, reason: r)) }
        if f.genericParameterClause != nil || f.genericWhereClause != nil { return fail("generic methods are not forwardable") }
        if f.modifiers.contains(where: { ["mutating", "consuming", "borrowing", "override"].contains($0.name.text) }) {
            return fail("`\(f.modifiers.trimmedDescription)` methods are not forwardable")
        }
        let isStatic = f.modifiers.contains { $0.name.tokenKind == .keyword(.static) || $0.name.tokenKind == .keyword(.class) }
        let nonisolated = f.modifiers.contains { $0.name.text == "nonisolated" }
        var attrs: [String] = []
        for a in f.attributes {
            guard let attr = a.as(AttributeSyntax.self) else { return fail("conditional attributes are not forwardable") }
            let an = ThunkGenerator.baseTypeName(attr.attributeName)
            if ["available", "MainActor", "discardableResult"].contains(an) { attrs.append(attr.trimmedDescription) }
        }
        var params: [String] = []
        var args: [String] = []
        for (i, p) in f.signature.parameterClause.parameters.enumerated() {
            if p.ellipsis != nil { return fail("variadic parameters are not forwardable") }
            let typeText = p.type.trimmedDescription
            if let at = p.type.as(AttributedTypeSyntax.self) {
                if !at.specifiers.isEmpty { return fail("`inout`/ownership parameters are not forwardable") }
                if at.attributes.contains(where: { $0.as(AttributeSyntax.self)?.attributeName.trimmedDescription == "autoclosure" }) {
                    return fail("`@autoclosure` parameters are not forwardable")
                }
            }
            if typeMentionsPrivate(typeText, c) { return fail("its signature mentions a private type") }
            let label = p.firstName.text
            let local = "p\(i)"
            let def = p.defaultValue.map { " = " + $0.value.trimmedDescription } ?? ""
            params.append("\(label) \(local): \(typeText)\(def)")
            args.append(label == "_" ? local : "\(label): \(local)")
        }
        let effects = f.signature.effectSpecifiers
        if effects?.throwsClause?.throwsSpecifier.tokenKind == .keyword(.rethrows) { return fail("`rethrows` methods are not forwardable") }
        let isAsync = effects?.asyncSpecifier != nil
        let throwsText = effects?.throwsClause?.trimmedDescription
        var sig = "func \(valuePrefix)\(name)(\(params.joined(separator: ", ")))"
        if isAsync { sig += " async" }
        if let t = throwsText { sig += " \(t)" }
        if let r = f.signature.returnClause {
            if typeMentionsPrivate(r.type.trimmedDescription, c) { return fail("its return type mentions a private type") }
            sig += " -> \(r.type.trimmedDescription)"
        }
        let call = (throwsText != nil ? "try " : "") + (isAsync ? "await " : "") + "\(name)(\(args.joined(separator: ", ")))"
        let prefix = (attrs.isEmpty ? "" : attrs.joined(separator: " ") + " ")
            + (nonisolated ? "nonisolated " : "") + (isStatic ? "static " : "")
        return .success("\(prefix)\(sig) { \(call) }")
    }

    /// Factory forwarders for a private View struct: one per explicit `init`, else the memberwise
    /// init derived from its stored properties (each with its declared default).
    static func factoryForwarders(_ s: StructDeclSyntax, callSites: [CallShape], catalog c: Catalog)
        -> Result<[String], ForwardFailure> {
        let typeName = s.name.text
        func fail(_ r: String) -> Result<[String], ForwardFailure> { .failure(.init(member: typeName, reason: r)) }
        let inits = s.memberBlock.members.compactMap { $0.decl.as(InitializerDeclSyntax.self) }
        var out: [String] = []
        if !inits.isEmpty {
            for i in inits {
                if i.optionalMark != nil { return fail("failable init is not forwardable") }
                if i.genericParameterClause != nil { return fail("generic init is not forwardable") }
                if isPrivateModifier(i.modifiers) { continue }   // not callable from the parent either
                var params: [String] = [], args: [String] = []
                for (k, p) in i.signature.parameterClause.parameters.enumerated() {
                    if p.ellipsis != nil { return fail("variadic init is not forwardable") }
                    if let at = p.type.as(AttributedTypeSyntax.self), !at.specifiers.isEmpty { return fail("inout init is not forwardable") }
                    let t = p.type.trimmedDescription
                    if typeMentionsPrivate(t, c) { return fail("init signature mentions a private type") }
                    if t.contains("@autoclosure") { return fail("`@autoclosure` init is not forwardable") }
                    let def = p.defaultValue.map { " = " + $0.value.trimmedDescription } ?? ""
                    let label = p.firstName.text
                    params.append("\(label) p\(k): \(t)\(def)")
                    args.append(label == "_" ? "p\(k)" : "\(label): p\(k)")
                }
                let eff = i.signature.effectSpecifiers
                let isAsync = eff?.asyncSpecifier != nil
                let thr = eff?.throwsClause?.trimmedDescription
                var sig = "func \(factoryPrefix)\(typeName)(\(params.joined(separator: ", ")))"
                if isAsync { sig += " async" }
                if let thr { sig += " \(thr)" }
                let call = (thr != nil ? "try " : "") + (isAsync ? "await " : "") + "\(typeName)(\(args.joined(separator: ", ")))"
                out.append("\(sig) -> AnyView { AnyView(\(call)) }")
            }
            guard !out.isEmpty else { return fail("no non-private init") }
            return .success(out)
        }
        // Memberwise: the parameter list is derived from the stored properties IN DECLARATION ORDER.
        // A defaulted property (initializer / optional var / auto-initialized wrapper) is included only
        // when some call site actually passes it, so an untypeable defaulted property the parent never
        // passes doesn't block forwarding. A trailing closure at a call site would bind positionally,
        // so it's refused here (explicit inits above handle it exactly).
        if callSites.contains(where: { $0.hasTrailingClosure }) {
            return fail("trailing-closure construction of a memberwise-init private view")
        }
        let usedLabels = Set(callSites.flatMap { $0.labels })
        var params: [String] = [], args: [String] = []
        var k = 0
        let autoInitWrappers: Set<String> = ["Environment", "EnvironmentObject", "Namespace", "FocusState",
                                             "GestureState", "Query", "FetchRequest", "SectionedFetchRequest",
                                             "ScaledMetric", "FocusedValue", "FocusedObject"]
        for member in s.memberBlock.members {
            guard let v = member.decl.as(VariableDeclSyntax.self) else { continue }
            if v.modifiers.contains(where: { $0.name.tokenKind == .keyword(.static) || $0.name.text == "lazy" }) { continue }
            let wrapper = v.attributes.compactMap { $0.as(AttributeSyntax.self) }.first
            let wrapperName = wrapper.map { ThunkGenerator.baseTypeName($0.attributeName) }
            let isLet = v.bindingSpecifier.tokenKind == .keyword(.let)
            for b in v.bindings {
                guard let name = b.pattern.as(IdentifierPatternSyntax.self)?.identifier.text else {
                    return fail("destructured stored property")
                }
                if let acc = b.accessorBlock {
                    // A getter/`get`/`set` block → computed (not in the init). Observers stay stored.
                    guard case .accessors(let list) = acc.accessors,
                          list.allSatisfy({ ["willSet", "didSet"].contains($0.accessorSpecifier.text) }) else { continue }
                }
                if isLet && b.initializer != nil { continue }                  // never in the memberwise init
                let annotated = b.typeAnnotation?.type.trimmedDescription
                let hasDefault = b.initializer != nil || wrapper?.arguments != nil
                    || (annotated?.hasSuffix("?") == true && !isLet)
                    || autoInitWrappers.contains(wrapperName ?? "")
                let used = usedLabels.contains(name)
                if hasDefault && !used { continue }
                var t: String
                switch wrapperName {
                case nil, "State", "StateObject", "ObservedObject", "Bindable", "AppStorage", "SceneStorage":
                    guard let ty = annotated ?? b.initializer.flatMap({ inferredType(of: $0.value) }) else {
                        return fail("stored property `\(name)` has no explicit type")
                    }
                    t = ty
                case "Binding":
                    guard let ty = annotated else { return fail("`@Binding` property `\(name)` has no explicit type") }
                    t = "Binding<\(ty)>"
                default:
                    return fail("stored property `\(name)` uses `@\(wrapperName!)`, whose init parameter type is unknown")
                }
                if typeMentionsPrivate(t, c) { return fail("stored property `\(name)` mentions a private type") }
                var def = b.initializer.map { " = " + $0.value.trimmedDescription } ?? ""
                if def.isEmpty, t.hasSuffix("?"), !isLet { def = " = nil" }
                if let ta = b.typeAnnotation?.type, Self.isFunctionType(ta) { t = "@escaping " + t }
                params.append("\(name) p\(k): \(t)\(def)")
                args.append("\(name): p\(k)")
                k += 1
            }
        }
        out.append("func \(factoryPrefix)\(typeName)(\(params.joined(separator: ", "))) -> AnyView { AnyView(\(typeName)(\(args.joined(separator: ", ")))) }")
        return .success(out)
    }

    static func isFunctionType(_ t: TypeSyntax) -> Bool {
        if t.is(FunctionTypeSyntax.self) { return true }
        if let a = t.as(AttributedTypeSyntax.self) { return a.baseType.is(FunctionTypeSyntax.self) }
        return false
    }

    // MARK: - Compact fallback block

    /// Shrink a legacy PATCH-THUNKS block that must stay in a developer file (a private View TYPE, or
    /// a view with a member that can't be forwarded) to its minimum: the 20-line banner and every
    /// `///` doc comment go, the per-view "why" becomes one precise line naming each blocking member
    /// and reason, and for a private View type's FULL thunk every helper method that is just `[:]`
    /// is dropped (its replacement passes `{ [:] }` instead). Pure presentation — markers, imports,
    /// the replacement and every non-empty helper are byte-for-byte what the legacy block carries,
    /// and the native-shell fingerprint strips the whole block either way.
    public static func compactInFileThunkBlock(_ block: String, factoredViews: [String], fullViews: [String],
                                               blockers: [String: [String: String]]) -> String {
        let lines = block.components(separatedBy: "\n")
        guard let first = lines.first, first == ThunkGenerator.sameFileBeginMarker,
              let ifIdx = lines.firstIndex(of: "#if canImport(SwiftUI)") else { return block }
        var out: [String] = [first]
        out.append("// Kept in this file because Swift `private` access is file-scoped and these can't be forwarded")
        out.append("// to Patch/Generated/. Remove all Patch code with `patchcli unprepare`.")
        for v in fullViews.sorted() {
            out.append("// \(v): `private`/`fileprivate` View type — its thunk can't live in another file.")
        }
        for v in factoredViews.sorted() {
            let reasons = (blockers[v] ?? [:]).sorted { $0.key < $1.key }
                .map { "`\($0.key)` (\($0.value))" }.joined(separator: "; ")
            out.append("// \(v): can't forward \(reasons.isEmpty ? "a private member" : reasons).")
        }
        for line in lines[ifIdx...] {
            let t = line.trimmingCharacters(in: .whitespaces)
            if t.hasPrefix("///") || t == ThunkGenerator.doNotEditFooter { continue }
            out.append(line)
        }
        var text = out.joined(separator: "\n")
        // Collapse runs of blank lines left behind by removed doc comments.
        while text.contains("\n\n\n") { text = text.replacingOccurrences(of: "\n\n\n", with: "\n\n") }
        return pruneEmptyHelpers(text, fullViews: Set(fullViews))
    }

    /// For each view whose FULL thunk (replacement + helpers) is in `text`, drop helper methods whose
    /// body is exactly `[:]` and point the replacement's closure at `[:]` directly.
    static func pruneEmptyHelpers(_ text: String, fullViews: Set<String>) -> String {
        guard !fullViews.isEmpty else { return text }
        let tree = Parser.parse(source: text)
        guard !tree.hasError else { return text }
        let helperNames: Set<String> = [ThunkGenerator.slotsMethodName, ThunkGenerator.tokensMethodName,
                                        ThunkGenerator.rowSlotsMethodName, ThunkGenerator.actionSlotsMethodName,
                                        ThunkGenerator.effectSlotsMethodName, ThunkGenerator.callbackSlotsMethodName]
        final class F: SyntaxVisitor {
            let fullViews: Set<String>; let helperNames: Set<String>
            var emptyByView: [String: Set<String>] = [:]
            var removals: [Range<Int>] = []
            var replacements: [(Range<Int>, String)] = []
            var replacementCalls: [(view: String, method: String, range: Range<Int>)] = []
            init(_ f: Set<String>, _ h: Set<String>) { fullViews = f; helperNames = h; super.init(viewMode: .sourceAccurate) }
            override func visit(_ e: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
                let name = e.extendedType.trimmedDescription
                guard fullViews.contains(name) else { return .skipChildren }
                for m in e.memberBlock.members {
                    guard let f = m.decl.as(FunctionDeclSyntax.self), helperNames.contains(f.name.text),
                          let body = f.body, body.statements.count == 1,
                          let dict = body.statements.first?.item.as(DictionaryExprSyntax.self),
                          dict.content.is(TokenSyntax.self) else { continue }
                    emptyByView[name, default: []].insert(f.name.text)
                    removals.append(m.position.utf8Offset..<m.endPosition.utf8Offset)
                }
                return .visitChildren
            }
            override func visit(_ c: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
                // `self.__patchSlots()` inside a replacement closure.
                if let ma = c.calledExpression.as(MemberAccessExprSyntax.self),
                   ma.base?.trimmedDescription == "self", helperNames.contains(ma.declName.baseName.text),
                   c.arguments.isEmpty {
                    var p = c.parent
                    while let q = p, !q.is(ExtensionDeclSyntax.self) { p = q.parent }
                    if let ext = p?.as(ExtensionDeclSyntax.self) {
                        replacementCalls.append((ext.extendedType.trimmedDescription, ma.declName.baseName.text,
                                                 c.positionAfterSkippingLeadingTrivia.utf8Offset..<c.endPositionBeforeTrailingTrivia.utf8Offset))
                    }
                }
                return .visitChildren
            }
        }
        let f = F(fullViews, helperNames)
        f.walk(tree)
        var edits: [(Range<Int>, String)] = f.removals.map { ($0, "") }
        for call in f.replacementCalls where f.emptyByView[call.view]?.contains(call.method) == true {
            edits.append((call.range, "[:]"))
        }
        guard !edits.isEmpty else { return text }
        var bytes = Array(text.utf8)
        for (r, rep) in edits.sorted(by: { $0.0.lowerBound > $1.0.lowerBound }) {
            bytes.replaceSubrange(r, with: Array(rep.utf8))
        }
        var result = String(decoding: bytes, as: UTF8.self)
        // Drop now-empty helper extensions (`extension X {` + blank lines + `}`).
        for v in fullViews {
            let pattern = "extension \(NSRegularExpression.escapedPattern(for: v)) \\{\\s*\\}\\n*"
            if let re = try? NSRegularExpression(pattern: pattern) {
                result = re.stringByReplacingMatches(in: result, range: NSRange(result.startIndex..., in: result), withTemplate: "")
            }
        }
        while result.contains("\n\n\n") { result = result.replacingOccurrences(of: "\n\n\n", with: "\n\n") }
        return ThunkGenerator.parses(result) ? result : text
    }

    // MARK: - Block rendering / stripping

    /// Render the in-file forwarder block for one file: one extension per forwarded view (sorted),
    /// wrapped in the BEGIN/END markers. `views` maps view name → its sorted forwarder decls.
    public static func renderBlock(views: [(name: String, forwarders: [String])]) -> String {
        var out = beginMarker + "\n"
        out += "// Forwards the private members Patch/Generated/ uses; changes only when that set does. Remove: `patchcli unprepare`.\n"
        for (name, fwds) in views.sorted(by: { $0.name < $1.name }) {
            if fwds.isEmpty {
                out += "// \(name): no private members needed.\n"
                continue
            }
            out += "extension \(name) {\n"
            for d in fwds { out += "    \(d)\n" }
            out += "}\n"
        }
        out += endMarker + "\n"
        return out
    }

    /// Remove a previously-generated forwarder block (BEGIN..END inclusive, plus the blank lines the
    /// generator put before it). Mirrors `ThunkGenerator.stripSameFileBlock` exactly (same whitespace
    /// accounting) so a strip → re-append cycle is a fixed point. A BEGIN with no END is left alone.
    public static func stripBlock(from source: String) -> String {
        guard let beginRange = source.range(of: beginMarker),
              let endRange = source.range(of: endMarker, range: beginRange.upperBound..<source.endIndex) else {
            return source
        }
        var idx = endRange.upperBound
        if idx < source.endIndex, source[idx] == "\n" { idx = source.index(after: idx) }
        var head = String(source[source.startIndex..<beginRange.lowerBound])
        while head.hasSuffix("\n") || head.hasSuffix(" ") { head.removeLast() }
        let tail = String(source[idx..<source.endIndex])
        return tail.isEmpty ? head + "\n" : head + "\n" + tail
    }

    /// Strip EVERY prepare-generated in-file block (the PATCH-ROUTE native-fallback block, the
    /// forwarder block and a legacy / fallback PATCH-THUNKS block), in any order. The route block
    /// is prepare's last append, so it is removed first (byte-exact when it is the file's suffix).
    public static func stripAllGeneratedBlocks(from source: String) -> String {
        var s = ThunkGenerator.stripRouteFallbackBlock(from: source)
        for _ in 0..<4 {   // bounded: at most one of each is ever generated
            let next = ThunkGenerator.stripRouteFallbackBlock(
                from: stripBlock(from: ThunkGenerator.stripSameFileBlock(from: s)))
            if next == s { break }
            s = next
        }
        return s
    }

    // MARK: - Body-edit removal (unprepare / excluded files)

    /// Remove prepare's body edits from `var body: some View` in the given View types (all View
    /// types when `onlyTypes` is nil): the `__patchRoute { … }` wrapper and a legacy `dynamic`
    /// modifier (an older CLI's edit). Exact inverse of both — nothing else moves. Returns the new
    /// text and the type names whose body changed. (Name kept for callers; see
    /// `ThunkGenerator.unrouteBodies`.)
    public static func removeDynamic(from source: String, onlyTypes: Set<String>?) -> (text: String, types: [String]) {
        ThunkGenerator.unrouteBodies(in: source, onlyTypes: onlyTypes)
    }
}

// MARK: - Scope-aware reference scanner

/// Walks a rendered helper-methods extension and records, for every reference to a private member
/// of the view, the byte-range edit that retargets it to its forwarder. Any reference it cannot
/// retarget with certainty (shadowed name, key path, implicit member, uncataloged private, private
/// type outside a constructor call) becomes a BLOCKER — the whole view then keeps same-file
/// placement.
final class ReferenceRewriteScanner: SyntaxVisitor {
    let c: PatchAccessForwarding.Catalog
    private(set) var edits: [(range: Range<Int>, replacement: String)] = []
    private(set) var usages = Set<PatchAccessForwarding.Usage>()
    private(set) var blockers: [String: String] = [:]
    private(set) var factoryCallSites: [String: [PatchAccessForwarding.CallShape]] = [:]

    init(catalog: PatchAccessForwarding.Catalog) {
        self.c = catalog
        super.init(viewMode: .sourceAccurate)
    }

    private var instanceVarNames: Set<String> { Set(c.vars.values.filter { !$0.isStatic }.map(\.name)) }
    private func isInstanceFunc(_ n: String) -> Bool {
        c.funcs[n]?.contains { !$0.modifiers.contains { $0.name.tokenKind == .keyword(.static) } } ?? false
    }
    private func isStaticMember(_ n: String) -> Bool {
        (c.vars[n]?.isStatic ?? false)
            || (c.funcs[n]?.contains { $0.modifiers.contains { $0.name.tokenKind == .keyword(.static) } } ?? false)
    }

    private func rename(_ token: TokenSyntax, to replacement: String) {
        let start = token.positionAfterSkippingLeadingTrivia.utf8Offset
        let end = token.endPositionBeforeTrailingTrivia.utf8Offset
        edits.append((start..<end, replacement))
    }

    private func block(_ name: String, _ reason: String) {
        if blockers[name] == nil { blockers[name] = reason }
    }

    override func visit(_ node: DeclReferenceExprSyntax) -> SyntaxVisitorContinueKind {
        let text = node.baseName.text
        let memberParent = node.parent?.as(MemberAccessExprSyntax.self)
        let isDeclName = memberParent?.declName.id == node.id

        // `$name` projection (free or `self.$name`).
        if text.hasPrefix("$"), text.count > 1 {
            let base = String(text.dropFirst())
            guard c.allPrivateMemberNames.contains(text) || c.allPrivateMemberNames.contains(base) else { return .visitChildren }
            if isDeclName, memberParent?.base?.as(DeclReferenceExprSyntax.self)?.baseName.text != "self" {
                return .visitChildren
            }
            guard let v = c.vars[base], !v.isStatic else {
                block(text, "declared outside this view's file or not a property wrapper"); return .visitChildren
            }
            rename(node.baseName, to: PatchAccessForwarding.projectionPrefix + base)
            usages.insert(.projection(base))
            return .visitChildren
        }

        if isDeclName, let mp = memberParent {
            let baseText = mp.base?.trimmedDescription
            if baseText == "self" {
                guard c.allPrivateMemberNames.contains(text) else { return .visitChildren }
                resolveInstance(text, token: node.baseName)
            } else if baseText == "Self" || baseText == c.viewName {
                guard isStaticMember(text) else {
                    if c.allPrivateMemberNames.contains(text) { block(text, "static member declared outside this view's file") }
                    return .visitChildren
                }
                rename(node.baseName, to: PatchAccessForwarding.valuePrefix + text)
                usages.insert(c.funcs[text] != nil ? .function(text) : .value(text))
            } else if mp.base == nil, isStaticMember(text) {
                block(text, "implicit-member reference to a private static")
            } else if c.otherTypePrivateMemberNames.contains(text), !baseIsProvablyForeign(mp.base) {
                block(text, "a `private`/`fileprivate` member of another type in this file")
            }
            return .visitChildren
        }

        // Free identifier (or the base of a member access).
        if c.privateViewTypes[text] != nil {
            if let call = node.parent?.as(FunctionCallExprSyntax.self), call.calledExpression.id == node.id {
                switch Self.shadowState(text, at: Syntax(node)) {
                case .shadowed: return .visitChildren
                case .ambiguous: block(text, "a local of the same name makes the reference ambiguous"); return .visitChildren
                case .none: break
                }
                rename(node.baseName, to: PatchAccessForwarding.factoryPrefix + text)
                usages.insert(.factory(text))
                factoryCallSites[text, default: []].append(.init(
                    labels: call.arguments.compactMap { $0.label?.text },
                    hasTrailingClosure: call.trailingClosure != nil || !call.additionalTrailingClosures.isEmpty))
            } else {
                block(text, "private View type used outside a constructor call")
            }
            return .visitChildren
        }
        if c.privateTypeNames.contains(text) {
            if Self.shadowState(text, at: Syntax(node)) != .shadowed { block(text, "private type referenced by the thunk") }
            return .visitChildren
        }
        if c.filePrivateGlobals.contains(text), !c.allPrivateMemberNames.contains(text) {
            if Self.shadowState(text, at: Syntax(node)) != .shadowed { block(text, "a file-private global") }
            return .visitChildren
        }
        guard c.allPrivateMemberNames.contains(text) else { return .visitChildren }
        switch Self.shadowState(text, at: Syntax(node)) {
        case .shadowed: return .visitChildren          // a local — not the member
        case .ambiguous: block(text, "a local of the same name makes the reference ambiguous"); return .visitChildren
        case .none: break
        }
        resolveInstance(text, token: node.baseName)
        return .visitChildren
    }

    /// The member-access base is `self.m` / `m` (a view member) whose type is declared in ANOTHER file,
    /// so `base.name` can't be a file-private member of a type in this file.
    private func baseIsProvablyForeign(_ base: ExprSyntax?) -> Bool {
        guard let base else { return false }
        var memberName: String?
        if let d = base.as(DeclReferenceExprSyntax.self) { memberName = d.baseName.text }
        else if let m = base.as(MemberAccessExprSyntax.self), m.base?.trimmedDescription == "self" { memberName = m.declName.baseName.text }
        guard let n = memberName, let t = c.memberBaseTypes[n] else { return false }
        return !c.fileDeclaredTypeNames.contains(t)
    }

    private func resolveInstance(_ text: String, token: TokenSyntax) {
        if instanceVarNames.contains(text) {
            rename(token, to: PatchAccessForwarding.valuePrefix + text)
            usages.insert(.value(text))
        } else if isInstanceFunc(text) {
            rename(token, to: PatchAccessForwarding.valuePrefix + text)
            usages.insert(.function(text))
        } else {
            block(text, "declared outside this view's file")
        }
    }

    override func visit(_ node: IdentifierTypeSyntax) -> SyntaxVisitorContinueKind {
        let n = node.name.text
        if c.privateTypeNames.contains(n) || c.privateViewTypes[n] != nil {
            block(n, "private type used in a type position")
        }
        return .visitChildren
    }

    override func visit(_ node: KeyPathPropertyComponentSyntax) -> SyntaxVisitorContinueKind {
        let n = node.declName.baseName.text
        if c.allPrivateMemberNames.contains(n) { block(n, "key path to a private member") }
        return .visitChildren
    }

    // MARK: Shadowing

    /// Whether `name` is (or may be) bound by a local declaration in any lexical scope enclosing
    /// `node`: closure params/captures, locals in an enclosing code block, `if let`/`guard let`/
    /// `while let` bindings, `for` patterns, `case let` patterns, `catch` bindings, and the enclosing
    /// generated method's own parameters. Conservative by design.
    enum Shadow { case none, shadowed, ambiguous }

    /// Whether `name` at `node` resolves to a LOCAL (closure param/capture, block-local, `if let`/
    /// `guard let`/`while let`/`for`/`case`/`catch` binding, enclosing method param) — `.shadowed`
    /// (leave it alone), to the member — `.none` (retarget it) — or can't be told apart syntactically
    /// (e.g. the RHS of `if let x = x`) — `.ambiguous` (refuse to forward the view).
    static func shadowState(_ name: String, at node: Syntax) -> Shadow {
        func contains(_ outer: SyntaxProtocol?, _ inner: Syntax) -> Bool {
            guard let outer else { return false }
            let r = outer.position.utf8Offset..<outer.endPosition.utf8Offset
            return r.contains(inner.position.utf8Offset)
        }
        var cur = node.parent
        while let c = cur {
            if let closure = c.as(ClosureExprSyntax.self), let sig = closure.signature, !contains(sig, node) {
                if let params = sig.parameterClause {
                    switch params {
                    case .simpleInput(let list):
                        if list.contains(where: { $0.name.text == name }) { return .shadowed }
                    case .parameterClause(let clause):
                        if clause.parameters.contains(where: { $0.firstName.text == name || $0.secondName?.text == name }) { return .shadowed }
                    }
                }
                if let cap = sig.capture, cap.items.contains(where: {
                    $0.trimmedDescription.split(whereSeparator: { !($0.isLetter || $0.isNumber || $0 == "_") }).contains { $0 == name }
                }) {
                    return .shadowed
                }
            }
            if let list = c.as(CodeBlockItemListSyntax.self) {
                for item in list {
                    let declares: Bool
                    if let v = item.item.as(VariableDeclSyntax.self) { declares = bindsName(Syntax(v), name) }
                    else if let f = item.item.as(FunctionDeclSyntax.self) { declares = f.name.text == name }
                    else if let g = item.item.as(GuardStmtSyntax.self) { declares = bindsName(Syntax(g.conditions), name) }
                    else { declares = false }
                    if declares { return contains(item, node) ? .ambiguous : .shadowed }
                }
            }
            if let i = c.as(IfExprSyntax.self), bindsName(Syntax(i.conditions), name) {
                if contains(i.body, node) { return .shadowed }
                if contains(i.conditions, node) { return .ambiguous }
            }
            if let w = c.as(WhileStmtSyntax.self), bindsName(Syntax(w.conditions), name) {
                if contains(w.body, node) { return .shadowed }
                if contains(w.conditions, node) { return .ambiguous }
            }
            if let f = c.as(ForStmtSyntax.self), bindsName(Syntax(f.pattern), name), contains(f.body, node) { return .shadowed }
            if let sc = c.as(SwitchCaseSyntax.self), bindsName(Syntax(sc.label), name) {
                return contains(sc.label, node) ? .ambiguous : .shadowed
            }
            if let k = c.as(CatchClauseSyntax.self), contains(k.body, node),
               name == "error" || bindsName(Syntax(k.catchItems), name) { return .shadowed }
            if let fn = c.as(FunctionDeclSyntax.self),
               fn.signature.parameterClause.parameters.contains(where: { $0.firstName.text == name || $0.secondName?.text == name }) {
                return .shadowed
            }
            cur = c.parent
        }
        return .none
    }

    private static func bindsName(_ node: Syntax, _ name: String) -> Bool {
        final class F: SyntaxVisitor {
            let name: String; var found = false
            init(_ n: String) { name = n; super.init(viewMode: .sourceAccurate) }
            override func visit(_ n: IdentifierPatternSyntax) -> SyntaxVisitorContinueKind {
                if n.identifier.text == name { found = true }
                return .skipChildren
            }
            // `if let name` shorthand (SE-0345) parses as an OptionalBindingCondition whose pattern is
            // an IdentifierPattern — covered above.
            override func visit(_ n: ClosureExprSyntax) -> SyntaxVisitorContinueKind { .skipChildren }
        }
        let f = F(name)
        f.walk(node)
        return f.found
    }
}
