// SPDX-License-Identifier: Apache-2.0

// UIKitGuestPreamble.swift — the shared allocator + Foundation-free flat-JSON input
// scanners baked into every UIKit guest module's `_PatchUIKit.swift` wrapper.
// =============================================================================
// This is the SAME marshalling the SwiftUI guest preamble uses (the allocator
// convention + the byte-level `_patchScan*` family that pull a view/cell's inputs
// out of the flat `{"title":"…","count":3}` blob the host writes). It's declared
// here as a constant so the UIKit guest is self-contained — it does NOT depend on
// the SwiftUI emitter's private wrapper string — while staying behaviorally
// identical to the proven SwiftUI scanners (Embedded-Swift-clean, whitespace-
// tolerant, byte-level). Kept deliberately minimal: only the scalar + scalar-array
// scanners a cell's flat model needs (a cell model is flat scalars by construction;
// a struct/enum field demotes the cell upstream).

extension UIKitGuestEmitter {
    static let preamble: String = """
    // Auto-generated by Patch — UIKit guest module. The lowered cell construction runs
    // in WASM here: it BUILDS a UIKitNode tree (via the `UI.` IR builder) and returns
    // the packed (ptr,len) of its JSON-encoded UIKitEmission. The native SDK UIKit host
    // reconstitutes real UIKit from that tree. DO NOT EDIT.
    //
    // ABI: uikit_configure[/__<Cell>](ptr,len) -> i64 = (outPtr<<32)|outLen.
    // Payload: UIKitEmbeddedJSON(UIKitEmission{root, coverage}) — Codable JSON shape.

    // MARK: - Allocator (SDK malloc/free convention)

    @_cdecl("patch_malloc")
    public func patch_malloc(_ size: Int32) -> UnsafeMutableRawPointer? {
        UnsafeMutableRawPointer.allocate(byteCount: Int(max(size, 1)), alignment: 8)
    }

    @_cdecl("patch_free")
    public func patch_free(_ ptr: UnsafeMutableRawPointer?) {
        ptr?.deallocate()
    }

    // MARK: - Packed (ptr,len) emit

    private func _patchEmit(_ bytes: [UInt8]) -> Int64 {
        let n = bytes.count
        let out = UnsafeMutableRawPointer.allocate(byteCount: max(n, 1), alignment: 8)
        let outBytes = out.assumingMemoryBound(to: UInt8.self)
        for i in 0..<n { outBytes[i] = bytes[i] }
        let outPtr = Int32(bitPattern: UInt32(UInt(bitPattern: out)))
        return (Int64(outPtr) << 32) | Int64(n)
    }

    // MARK: - Foundation-free flat-JSON input marshalling (same as the SwiftUI guest)

    private func _patchReadBytes(_ ptr: Int32, _ len: Int32) -> [UInt8] {
        guard len > 0, let base = UnsafePointer<UInt8>(bitPattern: Int(ptr)) else { return [] }
        return Array(UnsafeBufferPointer(start: base, count: Int(len)))
    }

    private func _patchFind(_ haystack: [UInt8], _ needle: [UInt8]) -> Int? {
        if needle.isEmpty || haystack.count < needle.count { return nil }
        let last = haystack.count - needle.count
        var i = 0
        while i <= last {
            var j = 0
            while j < needle.count, haystack[i + j] == needle[j] { j += 1 }
            if j == needle.count { return i }
            i += 1
        }
        return nil
    }

    private func _patchValueStart(_ s: [UInt8], _ key: String) -> Int? {
        let kb = Array("\\"\\(key)\\"".utf8)
        guard let k = _patchFind(s, kb) else { return nil }
        var i = k + kb.count
        while i < s.count, s[i] == 0x3A || s[i] == 0x20 || s[i] == 0x09 || s[i] == 0x0A || s[i] == 0x0D { i += 1 }
        return i < s.count ? i : nil
    }

    private func _patchScanString(_ s: [UInt8], _ key: String) -> String? {
        guard let start = _patchValueStart(s, key), s[start] == 0x22 else { return nil }
        var i = start + 1
        var out: [UInt8] = []
        while i < s.count {
            let c = s[i]
            if c == 0x5C, i + 1 < s.count {
                let n = s[i + 1]
                switch n {
                case 0x6E: out.append(0x0A)
                case 0x74: out.append(0x09)
                case 0x72: out.append(0x0D)
                case 0x62: out.append(0x08)
                case 0x66: out.append(0x0C)
                case 0x2F: out.append(0x2F)
                case 0x22: out.append(0x22)
                case 0x5C: out.append(0x5C)
                case 0x75 where i + 5 < s.count:
                    func hex(_ b: UInt8) -> UInt32? {
                        switch b {
                        case 0x30...0x39: return UInt32(b - 0x30)
                        case 0x41...0x46: return UInt32(b - 0x41 + 10)
                        case 0x61...0x66: return UInt32(b - 0x61 + 10)
                        default: return nil
                        }
                    }
                    if let h3 = hex(s[i+2]), let h2 = hex(s[i+3]), let h1 = hex(s[i+4]), let h0 = hex(s[i+5]),
                       let scalar = Unicode.Scalar(h3 << 12 | h2 << 8 | h1 << 4 | h0) {
                        out.append(contentsOf: Array(String(scalar).utf8))
                        i += 6; continue
                    }
                    out.append(n)
                default: out.append(n)
                }
                i += 2; continue
            }
            if c == 0x22 { break }
            out.append(c); i += 1
        }
        return String(decoding: out, as: UTF8.self)
    }

    private func _patchScanToken(_ s: [UInt8], _ key: String) -> String? {
        guard let start = _patchValueStart(s, key) else { return nil }
        var i = start
        var out: [UInt8] = []
        while i < s.count {
            let c = s[i]
            if c == 0x2C || c == 0x7D || c == 0x5D
                || c == 0x20 || c == 0x09 || c == 0x0A || c == 0x0D { break }
            out.append(c); i += 1
        }
        return out.isEmpty ? nil : String(decoding: out, as: UTF8.self)
    }

    private func _patchScanBool(_ s: [UInt8], _ key: String) -> Bool? {
        guard let t = _patchScanToken(s, key) else { return nil }
        if t == "true" { return true }
        if t == "false" { return false }
        return nil
    }
    private func _patchScanInt(_ s: [UInt8], _ key: String) -> Int? {
        _patchScanToken(s, key).flatMap { Int($0) }
    }
    private func _patchScanDouble(_ s: [UInt8], _ key: String) -> Double? {
        _patchScanToken(s, key).flatMap { Double($0) }
    }

    // MARK: - Foundation-free ARRAY-of-scalar input marshalling

    private func _patchArrayBody(_ s: [UInt8], _ key: String) -> (Int, Int)? {
        guard let start = _patchValueStart(s, key), start < s.count, s[start] == 0x5B else { return nil }
        var i = start + 1
        var depth = 1
        var inStr = false
        while i < s.count {
            let c = s[i]
            if inStr {
                if c == 0x5C { i += 2; continue }
                if c == 0x22 { inStr = false }
            } else {
                if c == 0x22 { inStr = true }
                else if c == 0x5B { depth += 1 }
                else if c == 0x5D { depth -= 1; if depth == 0 { return (start + 1, i) } }
            }
            i += 1
        }
        return nil
    }

    private func _patchArrayElements(_ s: [UInt8], _ lo: Int, _ hi: Int) -> [(Int, Int)] {
        var out: [(Int, Int)] = []
        var i = lo
        var elemStart = lo
        var depth = 0
        var inStr = false
        while i < hi {
            let c = s[i]
            if inStr {
                if c == 0x5C { i += 2; continue }
                if c == 0x22 { inStr = false }
            } else if c == 0x22 { inStr = true }
            else if c == 0x5B || c == 0x7B { depth += 1 }
            else if c == 0x5D || c == 0x7D { depth -= 1 }
            else if c == 0x2C && depth == 0 { out.append((elemStart, i)); elemStart = i + 1 }
            i += 1
        }
        if elemStart < hi { out.append((elemStart, hi)) }
        return out
    }

    private func _patchTrimRange(_ s: [UInt8], _ lo: Int, _ hi: Int) -> (Int, Int) {
        var a = lo, b = hi
        func ws(_ c: UInt8) -> Bool { c == 0x20 || c == 0x09 || c == 0x0A || c == 0x0D }
        while a < b, ws(s[a]) { a += 1 }
        while b > a, ws(s[b - 1]) { b -= 1 }
        return (a, b)
    }

    private func _patchScanIntArray(_ s: [UInt8], _ key: String) -> [Int]? {
        guard let (lo, hi) = _patchArrayBody(s, key) else { return nil }
        var out: [Int] = []
        for (es, ee) in _patchArrayElements(s, lo, hi) {
            let (a, b) = _patchTrimRange(s, es, ee)
            guard a < b else { continue }
            if let v = Int(String(decoding: s[a..<b], as: UTF8.self)) { out.append(v) } else { return nil }
        }
        return out
    }
    private func _patchScanDoubleArray(_ s: [UInt8], _ key: String) -> [Double]? {
        guard let (lo, hi) = _patchArrayBody(s, key) else { return nil }
        var out: [Double] = []
        for (es, ee) in _patchArrayElements(s, lo, hi) {
            let (a, b) = _patchTrimRange(s, es, ee)
            guard a < b else { continue }
            if let v = Double(String(decoding: s[a..<b], as: UTF8.self)) { out.append(v) } else { return nil }
        }
        return out
    }
    private func _patchScanBoolArray(_ s: [UInt8], _ key: String) -> [Bool]? {
        guard let (lo, hi) = _patchArrayBody(s, key) else { return nil }
        var out: [Bool] = []
        for (es, ee) in _patchArrayElements(s, lo, hi) {
            let (a, b) = _patchTrimRange(s, es, ee)
            guard a < b else { continue }
            let t = String(decoding: s[a..<b], as: UTF8.self)
            if t == "true" { out.append(true) } else if t == "false" { out.append(false) } else { return nil }
        }
        return out
    }
    private func _patchScanStringArray(_ s: [UInt8], _ key: String) -> [String]? {
        guard let (lo, hi) = _patchArrayBody(s, key) else { return nil }
        var out: [String] = []
        for (es, ee) in _patchArrayElements(s, lo, hi) {
            let (a, b) = _patchTrimRange(s, es, ee)
            guard a < b, s[a] == 0x22 else { return nil }
            var i = a + 1
            var bytes: [UInt8] = []
            while i < b {
                let c = s[i]
                if c == 0x5C, i + 1 < b {
                    let n = s[i + 1]
                    switch n {
                    case 0x6E: bytes.append(0x0A)
                    case 0x74: bytes.append(0x09)
                    case 0x72: bytes.append(0x0D)
                    case 0x62: bytes.append(0x08)
                    case 0x66: bytes.append(0x0C)
                    case 0x2F: bytes.append(0x2F)
                    case 0x22: bytes.append(0x22)
                    case 0x5C: bytes.append(0x5C)
                    default: bytes.append(n)
                    }
                    i += 2; continue
                }
                if c == 0x22 { break }
                bytes.append(c); i += 1
            }
            out.append(String(decoding: bytes, as: UTF8.self))
        }
        return out
    }

    // MARK: - Lowered cell constructions

    """
}
